### ISSUE TITLE
n command (go to next search result) is broken

### ISSUE THREAD

**Issue by mauke** [akhodakivskiy/VimFx#749] opened 2016-06-04 07:08 UTC
Steps to reproduce:

1. go to https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md
2. type <kbd>/</kbd> (start search mode), type `fixed`, hit <kbd>Enter</kbd>
3. hit <kbd>n</kbd>

Expected result: 
The first *Fixed* (under 0.16.1) is highlighted, then the next *Fixed* (under 0.16.0) is highlighted.

Actual result: 
Highlight stays on the first result. <kbd>Ctrl+g</kbd> works normally and moves to the next result. Hitting <kbd>n</kbd> again jumps back to the first result (within the current viewport, not the top of the page).
Keeping <kbd>n</kbd> held down makes the first search result within the current viewport flicker; sometimes the highlight visibly jumps down to other results for an instant. Releasing <kbd>n</kbd> has non-deterministic behavior: sometimes it goes to the second or third result (within the current viewport). Hitting <kbd>n</kbd> again goes back to the first result.

VimFx version: 0.16.1
Firefox version: 46.0.1
OS: Windows 7
Keyboard language: en_US (with some customizations around <kbd>AltGr</kbd>)
Worked before: 
Example URL(s):

**Comment by mauke** [comment] 2016-06-04 07:19
Oh, WTF. I just installed some older versions to see if I can pinpoint the exact version it broke:
- 0.16.1: broken
- 0.15.1: broken
- 0.14.3: works
- 0.15.0: works
- 0.15.1: works
- 0.16.1: works

... so now I have a working VimFx again and I can't reproduce the original problem. I'm going to close it for now and I'll let you know if it reappears.

**Comment by lydell** [comment] 2016-06-04 09:37
See also #747.

**Comment by mauke** [comment] 2016-06-04 11:29
I'm not sure what happened, but the issue is back. I changed nothing in my add-ons.

**Comment by lydell** [comment] 2016-06-05 10:10
Thanks for your report, but I can't reproduce this.

VimFx version: 0.16.1
Firefox version: 46.0.1, with a new Firefox profile
OS: Ubuntu 16.04
Keyboard language: en_US

**Comment by nathanmusoke** [comment] 2016-06-09 08:04
I have been intermittently experiencing a very similar issue. I had been waiting to determine the cause before opening an issue, but haven't been able to pin it down.

VimFx version: 0.17.0
Firefox version: 46.0.1
OS: Arch Linux
Keyboard language: en_US
Worked before: yes
Example URL(s): currently, searching for "go" on http://julialang.org/

Like I said, it's intermittent. I can add something to @mauke's report though: searching backwards works. This started around version 0.16.0, maybe 0.15.1. 


I also had some issues with `/` opening two search bars, but wasn't able to reproduce. I don't know if it's related.

**Comment by lydell** [comment] 2016-06-09 14:08
@mauke @nathanmusoke Could you please test in new Firefox profiles?

**Comment by nathanmusoke** [comment] 2016-06-10 02:07
I will try that. For now, I record addition observations:


Searching for "para" on http://julialang.org/ finds:
* 7 matches using `Ctrl+g`
* 3 matches using `N`
   * they are the two in links and one in a codesnippet
   * Pressing `N` while on the match in a code snippet finds the match in the preceding `h1` element. From there, `n` finds no other matches. 

Searching for "go" on http://julialang.org/ finds:
* 14 matches using `Ctrl+g`
* 6 matches using `N`
* This is not found: `<div class="header">Google Summer of Code</div>`. However, the match in the immediately following `<p>` element is.

**Comment by lydell** [comment] 2016-06-10 05:14
Sorry, I can't reproduce that either. As a workaround, you can disable the [`find_from_top_of_viewport`](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#find_from_top_of_viewport) pref.

**Comment by lydell** [comment] 2016-06-11 07:16
Closing until response.

**Closed by lydell** 2016-06-11 07:16 UTC

**Comment by nathanmusoke** [comment] 2016-06-18 11:17
Hi again - I've been testing on and off in new profiles. It took a while to show up, but it did just now.

**Comment by braeutigamj** [comment] 2017-06-30 07:16
Hello,
I think I have the same problem. It says "n: Überschrieben durch: Alle Tabs aktualisieren". But I can't find "Alle Tabs aktualisieren" in the configuration.

Thank you in advance.

**Comment by lydell** [comment] 2017-06-30 07:25
@braeutigamj Look harder. It’s there.

**Comment by braeutigamj** [comment] 2017-06-30 12:12
@lydell Thanks it was there... Now I know my problem. The field was set with "none2". There where some other fields with "none..". They had overwritten "n". I've deleted some field values. I don't know why they were set with none.
Thanks you for your help.
