### ISSUE TITLE
Last version broke Vimfx in Firefox 56

### ISSUE THREAD

**Issue by Dabsen** [akhodakivskiy/VimFx#902] opened 2017-11-20 18:28 UTC
My firefox auto-updated VimFx to 0.20.11 today. This new version just doesn't work at all under my Firefox 56: nothing works, not even the toolbar icon nor the buttons in the configuration page. Reverting to 0.20.10 fixed the issue. 
Is there a way to keep VimFx working for older firefox versions while still allowing it to work in Firefox 58 with legacy addons support, as the new version apparently does? I feel that the addon should remain easily accessible to those using Firefox 56 or Firefox ESR and shouldn't auto-break for those of us still happily using it.

**Comment by lydell** [comment] 2017-11-20 18:34
@lilydjwg Could you take a look at this?

**Comment by sugoiuguu** [comment] 2017-11-20 21:25
same here, could you look into it?

**Comment by lilydjwg** [comment] 2017-11-21 05:38
I can't reproduce this with Firefox 56.0.2 (alongside some other versions) on Linux x86_64. It works fine for me.

**Comment by dragon0** [comment] 2017-11-21 07:09
I'm having the same issue. Disabling NoScript fixed it.
@Dabsen how did you revert to 0.20.10?

**Comment by lilydjwg** [comment] 2017-11-21 07:19
I've installed NoScript and still couldn't reproduce. They both work fine.

@dragon0 You can find old versions here: https://addons.mozilla.org/firefox/addon/vimfx/versions/

(My Firefox 56 had automatically upgraded to 57.....)

**Comment by dragon0** [comment] 2017-11-21 07:28
Everything appears to be working for me now. Firefox 56, VimFX 0.20.11, NoScript 5.1.7.

I think reverting to 0.20.10 and back to 0.20.11 (maybe just remove/re-add VimFX) fixed it.

**Comment by GloverDonovan** [comment] 2017-11-21 20:31
VimFx 0.20.11 also broke things here on Waterfox 55.2.2 and GNU/Linux. Reinstalling fixed the issue.

I am not familiar with the code base but by any chance was something added / removed that breaks compatibility with previous installs? A variable that behaves differently depending on which version you have, for example?

**Comment by lydell** [comment] 2017-11-21 20:35
@GloverDonovan The only change was #901, and it looks completely safe. Do you see anything suspicious in the browser console? (`<c-J>` to open.)

**Comment by Dabsen** [comment] 2017-11-21 20:51
Strange. I re-updated to the latest version (from 0.21.10) and again, it 
didn't work. Then I removed vimfx completely, closed firefox, reopened 
it, and re-installed the latest version of vimfx; then it worked.  The 
weirdest thing is that I tried to reproduce the bug afterwards, by 
reinstalling 0.21.10, then upgrading, but now vimfx always seems to 
work. It makes little sense to me.

Btw my config is also Firefox 56.0.2 (Archlinux build), x86_64.

**Comment by GloverDonovan** [comment] 2017-11-21 20:57
I don't think I'll be able to get the error message since I already reinstalled VimFx.

In the console I get `NS_ERROR_UNEXPECTED` at `utils.js:282` when clicking on a page and `NS_ERROR_NOT_INITALIZED` at `message-manager.js:86` when opening a webpage from the location bar. Probably not related.

**Comment by lydell** [comment] 2017-11-21 21:01
My guess is that a Firefox restart is needed after updating, for some reason.

**Comment by GloverDonovan** [comment] 2017-11-21 21:07
I tried restarting my browser before and that did not fix the issue. I also tried disabling and re-enabling the addon (did not work). I had to uninstall VimFx and install it again before it started working.

Can anyone else confirm that Windows isn't affected? I have the same configuration on a Windows install and the update didn't break anything.

**Comment by Dabsen** [comment] 2017-11-21 22:08
I did try restarting Firefox, too, as well as disabling/enabling the 
extension. Only a clean reinstall solved the issue. I don't know if 
we'll get to the bottom of this, but for the time being, I'm reverting 
to 0.20.10 with auto-upgrade enabled to see if the problem reappears 
when FF upgrades vimfx to the latest version.

**Comment by dragon0** [comment] 2017-11-22 03:42
Just tried on Windows 10 with Firefox 56.0.2.

- Auto-update broke VimFX
- Reverting and restarting fixed it
- Re-installing 0.20.11 and restarting did **not** fix it
- Removing and re-adding VimFX fixed it

**Comment by lilydjwg** [comment] 2017-11-22 05:47
I've got the reverse: upgrading to 0.20.11 fixes and downgrading to 0.20.10 breaks....

The error seems to be `utils` (and maybe others) being `null` inside `events.js`.

**Comment by RaitaroH** [comment] 2017-11-22 13:48
Ah...
Linux Mint 17.3 64 bit
Waterfox 55.2.2 (64-bit)
VimFX 0.20.11

Had to reinstall VimFX too on 2 separate days. Restarting waterfox or closing it and open it back up seem to not have any impact. Right now I tried restarting waterfox and VimFX works...

**Comment by RaitaroH** [comment] 2018-01-28 05:56
I suppose I can just post here again.

VimFx version: Version 0.20.12
Waterfox: 56.0.2

Version 20.12 keeps breaking itself after I close the browser. When I open it back up vimfix isn't working anymore. I downgraded to 20.11 and it works fine again.

**Comment by lydell** [comment] 2018-01-28 09:43
@kevincox Have you had any problems with the new version?

**Comment by kevincox** [comment] 2018-01-28 15:17
@lydell I haven't noticed any problems with the latest version. I probably use a minority of the functionality (just tab management really, not too much of the in-page features).

I am using Firefox Developer Edition 59.

**Comment by RaitaroH** [comment] 2018-01-29 05:35
@lydell Ok so today my vimfx wasn't working again. I realinstalled .11, I restarted the browser a few times > it worked, then I manually updated to .12 > still working, then I restarted the PC > it was working.

**Comment by mroutis** [comment] 2018-02-23 20:05
@kevincox is it still working for you? There was a recent update in firefox (59.0b12) which deprecates the `legacy` addons functionality

**Comment by mroutis** [comment] 2018-02-23 20:08
![2018-02-23-14 05 23](https://user-images.githubusercontent.com/7363250/36614645-f73435c2-18a2-11e8-89be-3bbcefbd36d4.png)
is it the end?

**Comment by mroutis** [comment] 2018-02-23 20:19
sorry for the ping, @kevincox; the update just enabled the following flag `extensions.legacy.enable`, setting it to true let me use VimFx :heart_eyes:

**Comment by diebersa** [comment] 2018-05-16 05:55
@kevincox @mroutis 
I have tried to manually install the xpi of version 0.20.14 in Firefox 60 after setting `extensions.legacy.enable` to `true` in `about:config`, but it gives me the no compatible with Firefox Quantum message. Is this working for you?

**Comment by mroutis** [comment] 2018-05-16 15:28
not anymore @diebersa, I'm using Vimium in Firefox, is the closest to VimFx I found.

**Comment by kevincox** [comment] 2018-05-17 18:18
Most functionality still works on the latest versions however stable firefox doesn't support the `extensions.legacy.enable` preference. Try nightly/beta/developer.

**Closed** 2019-08-19 22:17 UTC
Labels: bug, cannot reproduce, discussion, help wanted, question
