### ISSUE TITLE
Going one step above or below is not working with any key setup

### ISSUE THREAD

**Issue by bad63r** [akhodakivskiy/VimFx#658] opened 2016-01-03 01:19 UTC
When you do www.google.com>search for arch linux srbija> click on arch linux srbija. And you wanna go one step back, you can'y do it with "[" or forword with oposite key or any key you set to do that function .
I think it is a bug, i discovered this cool addon a couple of weeks ago so may be it is just me. However in any case i hope you will find/tell me solution :) Keep a good work

**Comment by lydell** [comment] 2016-01-03 08:20
Duplicate of #563.

**Closed by lydell** 2016-01-03 08:20 UTC
