### ISSUE TITLE
`Follow_next` command (`]`) does not work on google.com

### ISSUE THREAD

**Issue by azuwis** [akhodakivskiy/VimFx#836] opened 2016-11-17 07:04 UTC
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.4
Firefox version: 50.0
OS: Linux (Debian Unstable), Windows 10
Keyboard language: US
Example URL (if any): https://www.google.com/

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Create a new Firefox profile (by run `firefox -P`)
2. Install vimfx from https://addons.mozilla.org/en-us/firefox/addon/vimfx/
3. Open https://www.google.com/
4. Search anything, e.g. `test`
5. Press `]`

Expected result: Go to next page

Actual result: Nothing happened. Follow_previous command (`[`) works fine.

**Comment by azuwis** [comment] 2016-11-17 07:24
Found the problem, remove `more` from `next_patterns`, and `follow_next` worked.

Should I close the issue?

**Comment by lydell** [comment] 2016-11-17 08:00
No, don't close it. It's a shame that `]` doesn't work out of the box on one of the most visited pages on the Internet.

**Comment by lolilolicon** [comment] 2016-11-18 02:24
One of the first things I put in my `config.js` was to fix `]` on Google Search,
```js
// config.js
vimfx.addOptionOverrides(
  [ ({hostname, searchParams}) => hostname === "www.google.com" && !searchParams.get("tbm"), {
      pattern_selector: "#pnprev, #pnnext",
      pattern_attrs: ["id"],
      prev_patterns: [/^pnprev$/],
      next_patterns: [/^pnnext$/],
    }
  ]
);
```
I don't think there's anything generic to extract from the Google page; it has to be a special case for the site.
Therefore, it's appropriate to put this in a configuration file.
However, it does kind of suck that every user has to repeat this configuration...
Perhaps VimFx should ship some default site configurations? For extremely popular sites only, of course.
Otherwise, a wiki page wouldn't be too bad, either.

**Comment by lydell** [comment] 2016-11-18 06:43
I'd be fine with adding a special case for Google. Are there any other known popular sites that might need special cases?

The bigger question: Perhaps the problem is that the algorithm for finding previous/next links is "wrong" and needs to be changed?

(Regarding a wiki page – feel free to create one!)

**Comment by lydell** [comment] 2016-11-30 07:13
What about this?

1. Add a mapping of some kind of URL patterns to CSS selectors.
2. When looking for the previous or next link, first check if the current URL matches one of the URL patterns. If it does, continue. Otherwise, fall back to current algorithms for finding the link.
3. There are two CSS selectors per URL pattern: One for the previous link, and one for the next link. Use one of them to find the link.

I'm thinking that we should add a few sites to this mapping by default (and encourage people to submit more to it?). Apart from that, the mapping should be modifiable with a config file.

I'm still interested in enhancing the current link finding algorithms, but I can't think of anything for the time being.

**Comment by lydell** [comment] 2016-12-04 12:59
Actually, the mapping could be very similar to how `addOptionOverrides` work. I'm thinking about something like this:

```js
[
  [ ({hostname, searchParams}) => hostname === "www.google.com" && !searchParams.get("tbm"),
    (window, prev) => window.document.getElementById(prev ? 'pnprev' : 'pnnext')
  ],
]
```

**Comment by lolilolicon** [comment] 2016-12-07 01:54
So it's like a higher precedence, more convenient `addOptionOverrides`? Does it enable bypassing broken `<link rel=prev/next`, as reported in #792?

**Comment by lydell** [comment] 2016-12-07 06:21
Yes, that's the idea.

**Comment by lydell** [comment] 2017-01-07 08:51
There does not seem to be very much interest here, and nobody has brought up any other site than Google, so I simply added a special-case for Google. We might revisit this issue in the future.

**Closed by lydell** 2017-01-07 08:51 UTC
Labels: enhancement, help wanted
