### ISSUE TITLE
Vimfx works pretty great but it block the "Nums" hotkeys from keyconfig.

### ISSUE THREAD

**Issue by ar1xwe** [akhodakivskiy/VimFx#657] opened 2015-12-31 08:53 UTC
! - SORRY ABOUT MY HORRIBLE ENGLISH, I'LL STILL TRY MY BEST - !

Take a look at this useful extension
http://forums.mozillazine.org/viewtopic.php?t=72994

User can write a script and bind any key as you want.

Just reset firefox and install those (Vimfx, keyconfig), and setting "1" : Jump to 1st tab.
and you can realized.Vimfx captured the "1" Keyboard Event before keyconfig...(Just in my mind).
Vimfx is pretty useful, but can it not blocking those shortcuts of keyconfig ?

by the way. Why vimfx didnt block the alphabet keys shortcut !? It's weird...

**Comment by lydell** [comment] 2015-12-31 09:13
Duplicate of #646.

**Closed by lydell** 2015-12-31 09:13 UTC
