### ISSUE TITLE
Scrolling with j/k broken in Firefox Developer Edition

### ISSUE THREAD

**Issue by Decoherence** [akhodakivskiy/VimFx#558] opened 2015-10-27 17:56 UTC
Using Firefox Developer edition 43.0a2 (2015-10-27), the scroll down/up keys aren't working. Pressing '?' confirms that j/k are assigned. This issue persists when multi-process is enabled/disabled.

VimFx works as expected on Firefox 41.0.2.

**Comment by lydell** [comment] 2015-10-27 19:20
I assume you use the stable version of VimFx (0.5.17), not the development version (develop branch). If so, this is duplicate of #378. If not, please tell me and we’ll re-open.

**Closed by lydell** 2015-10-27 19:20 UTC
