### ISSUE TITLE
Cannot "click" Bandcamp play/pause buttons using VimFx

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#672] opened 2016-01-18 22:32 UTC
Bandcamp is a popular musical platform which provides streaming/download services.  Consider [this page](https://thevisit1.bandcamp.com/), for example.  I am unable to "click" the play/pause buttons using VimFx.  Vimium, on the other hand, works fine.

**Comment by lydell** [comment] 2016-01-18 22:54
The problem is that VimFx gives double markers for each button there. As a workaround you can press `<space>` once to see the correct hint marker.

**Comment by d125q** [comment] 2016-01-19 11:05
Thanks.  However, the small buttons (the ones listed for all songs), get only 1 hint which does not play/pause the song.

**Comment by lydell** [comment] 2016-01-19 11:55
True. Do they work in Vimium?

**Comment by d125q** [comment] 2016-01-19 12:11
Now that you mention it, those do not seem to work in Vimium either.

**Comment by lydell** [comment] 2016-01-19 16:24
Bandcamp use terrible markup.

For the first case, the markup looks something like this:

```html
<a>
    <div class="playbutton"></div>
</a>
```

For the second case, the markup looks like this:

```html
<a>
    <div class="play_status"></div>
</a>
```

It's that inner `<div>` that has the event handler. The outer `<a>` is useless.

The first case "works" because the inner `<div>` has the word 'button' in the
class name, which is the most terrible heuristic VimFx uses to find "clickable"
elements. The second case hasn't, so it's not recognized.

It could be argued that VimFx shouldn't create hints for `<a>` with `href`, so
you at least get rid of the double hints, but many sites use such elements
together with JavaScript as a substitute for `<button>`s, such as the voting
buttons on StackExchange. I see no way of recognizing this case in a general
way. (I guess Vimium produces double hints as well, but just happens to show the
hint for the inner `<div>` on top.)

I suggest you contact the site and ask them to improve their accessibility. For
example, they could use something like this:

```html
<button type="button" class="playbutton">
    <span class="screen-reader-only">Play</span>
</button>
```

I'm going to close this one as wontfix (but a good PR would be accepted, though
I doubt there's anything that can be done here).

**Closed by lydell** 2016-01-19 16:24 UTC
Labels: enhancement
