### ISSUE TITLE
Multi-process detection is unreliable

### ISSUE THREAD

**Issue by LordJZ** [akhodakivskiy/VimFx#569] opened 2015-11-07 11:42 UTC
8d5fc55
Windows 10
Nightly 45.0a1 (2015-11-06)
e10s enabled

Put cursor into some <input> like github comment form, hit `i`. Instead of typing `i` VimFx turns on ignore mode.

**Comment by lydell** [comment] 2015-11-07 15:32
I’m not able to reproduce this on Trisquel 7 and Nightly 44.0a1 (2015-10-18) (45.0a1 is not available in my system yet).

It’s strange, though, that it only happens for `i`. There nothing special about that command or that key. Are you sure that you’ve not accidentally set the shortcut to `<force>i`? What happens if you assign some other key to the “Enter Ignore mode” command? What happens if you assign `i` to some other command?

**Comment by LordJZ** [comment] 2015-11-07 15:58
Oh, so it looks like it's suppressing any bound key when input/textarea is focused.

**Comment by lydell** [comment] 2015-11-07 16:01
Do you use some (Chinese) input method?

**Comment by LordJZ** [comment] 2015-11-07 16:15
I have single keyboard layout (QWERTY) and two languages (Russian, English) with English selected. This is also reproduced on clean profile Nightly 45, no e10s, 0.5.17.1 from AMO. Not reproduced on Beta 43, possibly specific 45 version issue?

**Comment by lydell** [comment] 2015-11-07 16:16
Thanks for your rigorous testing! It sure looks like a version 45 specific issue, then. Too bad I can’t test it out just yet.

**Comment by enricostano** [comment] 2015-11-10 15:19
Same regression here passing from `0.5.18` to `0.6.0`

FF dev edition 42.0a2 (2015-08-28)

**Comment by lydell** [comment] 2015-11-10 16:01
@enricostano Firefox 42 stable has been released. Why do you use that really old nightly?

**Comment by enricostano** [comment] 2015-11-10 16:20
@lydell mh... https://www.reddit.com/r/archlinux/comments/3ph83p/where_did_the_firefoxdeveloper_package_go/

Will test with latest version. Sorry.

**Comment by enricostano** [comment] 2015-11-10 16:33
Confirmed with FF dev edition 44.0a2 (2015-11-10), may I help posting some debug log?

**Comment by edrex** [comment] 2015-11-12 16:29
I see the issue with Arch Linux/Firefox Aurora 44.0a2/VimFX v0.6.1), but not on OS X with FF DE.

Is it perhaps Linux specific?

**Comment by finalfantasia** [comment] 2015-11-12 21:13
@edrex this issue is reproducible on OS X, too.

My environment:
  VimFx 0.6.2
  Firefox Developer Edition 44.0a2 (2015-11-12)
  OS X El Capitan 10.11.1

**Comment by edrex** [comment] 2015-11-12 23:17
weird, it works for me

**Comment by davidjb** [comment] 2015-11-18 06:14
Wth 0.6.2 on FF 43a02 with e10s enabled, I'm finding that if I type anywhere on a page (eg in this GitHub input field) my keystrokes are always interpreted as VimFx commands. Trying to remember to type "i" first, even if my cursor and focus has entered the most plain of text boxes, is very hard (eg I keep refreshing pages because I type words with "r" in them).  It wasn't this bad in the past -- certain pages like Google Docs etc didn't get detected but there were no issues on standard text boxes.

**Comment by lawrencetran1** [comment] 2015-11-18 06:31
I have to press i to type text into textarea and input.
Windows 10
FF DE 44.0a2
Vimfx 0.6.2

**Comment by lydell** [comment] 2015-11-18 07:54
I get it – _some_ people get this problem, on a variety of different operating systems and Firefox versions. This _is_ a bug. The problem is that I can't reproduce it.

**Comment by edrex** [comment] 2015-11-19 00:27
It is sounding like a configuration problem.

Confirmed: I created a new profile with `firefox --ProfileManager` and installed VimFx, and under that profile the issue isn't present.

Where does VimFx store its config? I'm assuming Firefox puts extension config in some SQLite DB since I can't locate it in the profile dir.

**Comment by LordJZ** [comment] 2015-11-19 00:35
I can reproduce it on clean profile.

**Comment by edrex** [comment] 2015-11-19 00:50
My mistake: I was using `firefox` instead of `firefox-aurora`. I still the see the issue with a clean profile under Aurora.

**Comment by lydell** [comment] 2015-11-20 06:11
In version 0.7.0, which just has been released, VimFx's toolbar button turns grey when focusing text inputs. I guess it stays green for you, though?

**Comment by Zpiritual** [comment] 2015-11-20 08:04
I can confirm it stays green during text input. Pressing i makes the icon red.

**Comment by lydell** [comment] 2015-11-20 08:40
Thanks, @Zpiritual. Then the cause of this bug has been pretty much confirmed. A bit simlified, `document.activeElement` is used to determine if key presses should activate VimFx commands, or be passed to the page (e.g. a text input). It feels like either VimFx somehow fails to recognize the currently active element as a text input, or Firefox somehow reports the wrong element as active.

**Comment by lydell** [comment] 2015-11-21 13:38
I’ve made a version of VimFx with keydown debug logging. It is 0.7.2 plus one [commit that adds a few `console.log` statements](https://github.com/akhodakivskiy/VimFx/commit/ca23b0e89d21985bf0294a63a97fd38594f21489).

[VimFx.txt](https://github.com/akhodakivskiy/VimFx/files/40828/VimFx.txt)

1. Download the above file
2. Rename it to VimFx.xpi
3. Install it in Firefox

It would be really nice if somebody who can reproduce the issue could try that version out, and report what gets logged into the browser console, when:

- pressing some key when a link in a web page is focused.
- pressing some key when a text input in a web page is focused.
- pressing some key when the address bar is focused.

**Comment by edrex** [comment] 2015-11-21 18:55
The custom build didn't exhibit the bug, so I tried the last few builds and found that 0.7.1 has the bug but 0.7.2 doesn't. Evidently it was fixed by 255ea5b6bb2. Yay?

**Comment by lydell** [comment] 2015-11-21 21:25
@edrex If commit 255ea5b fixed it for you, it feels like `MULTI_PROCESS` is set wrongly, because that commit got rid a usage of that variable in the part of the code failing in this issue. Currently, it is set to the value of `browser.tabs.remote.autostart`. Could you check in about:config what the value of that pref is for you? Also write whether you’re using multi-process or not. For me, that pref is `false` in non-multi-process and `true` in multi-process.

**Comment by lydell** [comment] 2015-11-22 15:20
It’d be super useful if people could answer these questions:

1. Can you reproduce the problem in 0.7.2 or later?
2. What is the value of `browser.tabs.remote.autostart` in about:config?
3. Do you have multi-process enabled?

**Comment by LordJZ** [comment] 2015-11-22 15:40
Oh, so that's the issue. `browser.tabs.remote.autostart` was deprecated in favor of `browser.tabs.remote.autostart.2` -- they do so regularly to force everyone to use e10s. And even then, you can change that option without actually having e10s enabled-state synced with it (it is synced on browser restart).

**Comment by lydell** [comment] 2015-11-22 16:07
Thanks! Then we need to find some other way to detect multi-process mode.

**Comment by edrex** [comment] 2015-11-23 17:50
`MULTI_PROCESS_ENABLED` seems to only have one use in HEAD, [choosing how to handle VimFx state when moving tabs between windows](https://github.com/akhodakivskiy/VimFx/blob/b2530d3a1fdbe7258471a001386b1722ebc17c2a/extension/lib/events.coffee#L157). I don't entirely understand that code block, but it seems like it might be possible to rework it to directly check `@oldVim == @vim` etc.

**Comment by lydell** [comment] 2015-11-23 18:42
@edrex You’re right: We should get rid of that last occurrence and hope that won’t ever need it again. The “move tab to another window” handling is really messy. I’m working right now on making it better, fixing some subtle bugs along the way (in order to be able to implement window commands #402.)

**Closed** 2015-11-30 12:44 UTC
Labels: bug

**Comment by lydell** [comment] 2015-12-03 10:43
For the record, checking `.browserTabsRemoteAutostart` on [nsIXULRuntime](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXULRuntime) seems to be the proper way of detecting multi-process.
