### ISSUE TITLE
Enable VimFx when document DOM is ready

### ISSUE THREAD

**Issue by gtrias** [akhodakivskiy/VimFx#688] opened 2016-02-04 15:18 UTC
Steps to reproduce:

1. Open web app like Hipchat
2. Try to input text to chat with anyone before the app is completely loaded

I'm having issues with some web apps because VimFx is capturing keyboard before page is loaded.
I'm expecting to insert text but the webapp hasn't give me the focus to input text already, so I'm trying to insert text and a lot of VimFx actions are triggered.

I think could be good to prevent some keystrokes like "refresh" until the document DOM is ready.

VimFx version: 
Firefox version: 44.0a2 
OS: Arch Linux x64
Keyboard language: Es
Worked before:  No

**Comment by lydell** [comment] 2016-02-04 17:58
I’m not going to register an account for every other random web service. Please give a URL to some of the other “web apps” you have problems with, that I can access without having to sign up.

Also, try to be more detailed.

- Did you focus a text input before trying to type text? If so, how: mouse, `f`, `gi`?
- Do you use autofocus prevention?
- Is the toolbar button greyed out when you start typing (indicating that your key presses will be passed into the text input rather than activating VimFx commands)?
- How do tell that the “the app is completely loaded”?
- How to you know that waiting for the “document DOM is ready” will solve anything?

Finally, why did you leave “VimFx version:” blank and why did you remove “Example URL(s):”?

**Comment by gtrias** [comment] 2016-02-05 09:17
To test what I meaning you can go here http://codepen.io/gtrias/pen/jWeEGR and start to typing before the page is fully loaded and you gain the focus.

- I didn't make manual focus by clicking, f or gi because I expect autofocus. Usually VimFx works very well but sometimes when I'm working anc change tab quickly I start to typing before I gain the focus and sometimes it causes to reload all the tabs or other unwanted VimFx actions.
- I don't have autofocus prevention.
- No the toolbar button is not grey already because I haven't gain autofocus yet since the page is not fully loaded and I don't have the autofocus.
- I thought it could exists a method to know when te page is full loaded like in javascript dom ready.
- I'm not sure if waiting DOM ready will fix this behavior. I just want to debate if it could be a workaround to prevent this unwanted VimFx behavior. It happens to me and other people I know using VimFx that sometimes when you are working and you are expecting to have the focus but you start typing before and the page is reloaded or any other VimFx action.

I didn't leave the VimFx version because I wasn't able to find it. I have 0.12.0 verion. And example url because I haven't any concrete one.

**Comment by elboletaire** [comment] 2016-02-05 10:07
+1 for this. Currently I have VimFX disabled due to the multiple problems with sites like Gmail, Facebook or, as said by @gtrias HipChat.

It usually happens when the input focuses after dom has been loaded, but there are some times where it fails with the entire page fully loaded and, in those cases, there's no more option than using the "ignore mode" or reloading the full page.

**Comment by lydell** [comment] 2016-02-06 16:21
@gtrias Thanks for your update! It’s so much easier to understand bug reports when there’s an example URL like in your second comment. Thanks!

So, basically three things happen when going to that CodePen link you provided, with some time passing between each step:

1. You start loading the page.
2. You see CodePen’s UI on screen.
3. One of the text inputs is autofocused using JavaScript.

During the time between step 2 and 3 you accidentally think that the text input has already been focused and start typing.

- In plain Firefox (without VimFx) you end up with for example `lass="foo"></p>` instead of `<p class="foo"></div>`.
- _With_ VimFx, the keypresses that you type “in the air” trigger VimFx commands. In the above example, `<` would trigger nothing, but `p` would paste-and-go to whatever happens to be in your clipboard.

That’s the problem you have, right? (Just checking to be 100% sure.)

Both with and without VimFx you could argue that this is CodePen’s problem, being so slow to get the autofocus done. But I think VimFx has the solution:

1. [Blacklist](https://github.com/akhodakivskiy/VimFx/blob/76d3d4eb60c9dba7c19d6b7f5da5d6947557cebd/documentation/options.md#blacklist) codepen.io (and other sites where the same thing happens for you). For example, add `*codepen.io*` to the blacklist option.

2. However, then you cannot blur the text input using `<escape>` the first time; you’d have to press `<s-escape>`. If that bothers you, you could change the shortcut to exit Ignore mode to `<escape>`. However, you might not want to let `<escape>` exit Ignore mode on _all_ sites. If so, change the shortcut for exiting Ignore mode to `<s-escape>  <escape>` and add the following to a [config file](https://github.com/akhodakivskiy/VimFx/blob/76d3d4eb60c9dba7c19d6b7f5da5d6947557cebd/documentation/config-file.md):

   ```js
   vimfx.addKeyOverrides(
     [ (location, mode) => mode === 'ignore' && location.hostname !== 'codepen.io',
       ['<escape>']
     ]
   )
   ```

   That enables `<escape>` to exit Ignore mode only on codepen.io.

However, there’s a small gotcha. Currently, VimFx enters Ignore mode too slowly on codepen.io, breaking the solution. Luckily, I have a fix for this, which I’ll push in a moment. So in the next version you should be able make VimFx behave the way you want on sites you choose.



@elboletaire 

> I have VimFX disabled

It is possible to [disable VimFx](https://github.com/akhodakivskiy/VimFx/blob/76d3d4eb60c9dba7c19d6b7f5da5d6947557cebd/documentation/questions-and-answers.md#how-do-i-disable-vimfx) on a per-site basis rather than entirely.

> multiple problems with sites like Gmail, Facebook or, as said by @gtrias HipChat

If you share what problems you have we can try to fix them :)

> It usually happens when the input focuses after dom has been loaded, but there are some times where it fails with the entire page fully loaded and, in those cases, there's no more option than using the "ignore mode" or reloading the full page.

I don’t understand this.

**Closed** 2016-02-06 16:31 UTC
Labels: unconfirmed

**Comment by elboletaire** [comment] 2016-02-19 10:06
Sorry to not answer before, too much work these days.

The issue is still there. When I'm on gmail writing an e-mail, after putting some words sometimes writing a word with the "R" tries to refresh the page. 

I say "sometimes" because there are some times where this does not happen. But this happens 95% of the time in gmail and hipchat for me, the reason I have it disabled (just in gmail and hipchat for now).

**Comment by lydell** [comment] 2016-02-19 10:21
@elboletaire Nothing has been released yet; that's why things "still" happen. Also, you didn't read the previous comments. The solution is to use Ignore mode (but it is not going to work 100% until the next version.)

**Comment by elboletaire** [comment] 2016-02-19 10:39
I see that you read what you want dude...

I've read the comments, I know about the ignore mode, I've blacklisted any google related site but you have not said (till now) that the version wasn't released yet.
