### ISSUE TITLE
Focus not properly detected

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#738] opened 2016-05-24 09:37 UTC
Steps to reproduce:

1. Open two tabs, one with a text input, the other without;
2. Focus the text input (you get into Ignore mode with a gray icon);
3. Move to the other tab;
4. Go back to the tab with the text input.

Expected result: VimFx should be in normal mode when switching to the other tab, and return to Ignore mode (gray icon) when returning to the tab with the text input.

Actual result: VmFx is in Normal mode in the tab with the text input (you have to refocus the text input in order to go in Ignore mode with a gray icon).  VimFx is in Normal mode in the new tab but shows a gray icon.

VimFx version: 0.15.1
Firefox version: 46.0.1
OS: Arch Linux
Keyboard language: en-us
Worked before: Yes
Example URL(s): Any two of which one has a text input

**Comment by guilhas** [comment] 2016-05-26 08:41
Hello,
Same here.

Nice add-on.

Thanks

**Comment by protist** [comment] 2016-05-26 09:10
This is a pretty major bug IMO, because I think I'm typing in a text box, but actually sending a whole bunch of random commands to the window. I really don't want to be clicking random links all over the page! (And yes, thanks for the excellent add-on generally!)

**Comment by lydell** [comment] 2016-05-26 09:21
Yes, it annoys me too. Don’t worry, it’ll be fixed! But right now life is in the way. I think you can go back to 0.15.0 to avoid the issue.

**Comment by protist** [comment] 2016-05-26 09:39
Thank you for that. Sorry, I didn't mean to sound like I was pestering you. I just installed 0.15.0 and it works fine. Thanks again for the great add-on!

**Comment by protist** [comment] 2016-05-27 03:04
Sorry, I just had this problem again in 0.15.0. 99% of the time it works fine, but I just had a single occasion where it failed again.

1. Start typing in a text box.
2. Switch tabs to a window with no text box selected.
3. Switch back.
4. Keystrokes go to VimFx, not the text box.

Even clicking in the text box again doesn't solve it. I have to click elsewhere in the page then back in the text box.

I don't normally have the icon enabled, but I did just to look at the grey. I had some odd results. In 1, it turned grey as expected. However, at 2, it flashes colour for a split-second, then goes grey. Then at 3, the icon is coloured, even if keystrokes are going to the text box as expected.

**Comment by light2yellow** [comment] 2016-05-27 13:51
Same.
@protist Any hacks to make text box work again after switching the tab or whatever? Except site blacklisting.

**Comment by lydell** [comment] 2016-05-27 16:44
I've pushed a fix, which I've used it the whole day without noticing any problems. I'll publish a new version this weekend.

**Comment by protist** [comment] 2016-05-28 11:12
@light2yellow I didn't really have a workaround.
@lydell Thank you! Great to hear!

**Comment by nathanmusoke** [comment] 2016-05-29 03:22
I've been having a similar problem sporadically over the last few days but hadn't pinned down how to reproduce it -- hopefully this will fix it. Thanks for the great add-on and the quick response time!

**Comment by 2hu** [comment] 2016-05-29 11:52
Where exactly can I download the older extension? I'm having problems with text boxes and I don't know what's causing it, if I switch tabs and return to the page where my cursor is inside the text box it completely ignores it and starts inputting VimFX shortcuts. I have to click outside of the text box then select the box again for it to recognize my writing.

**Comment by lydell** [comment] 2016-05-29 11:55
https://addons.mozilla.org/en-US/firefox/addon/vimfx/versions/

**Comment by lydell** [comment] 2016-05-29 18:30
Version 0.16.0 has just been published and is available at the above URL.

**Closed by lydell** 2016-05-29 18:30 UTC
Labels: bug

**Comment by protist** [comment] 2016-05-29 23:38
Thanks @lydell. It's working well for me. Also, this seems to have fixed the icon-colour bug.Thank you for the quick fix!

(Also, previously, I'd type `/` and the string I wanted to search for. Sometimes the first few characters for the string would be stolen as VimFx function keys. This update also seems to have fixed that.)

**Comment by Vinnl** [comment] 2016-05-30 09:38
You guys, just wanted to say I came to the issue tracker to report this issue, only to find that:

1. You had already identified it better than I had (I didn't know it was the result of tab switching), and
2. A fix had actually already been released.

I know I should just press one of the reaction buttons, but I thought it'd be nice to put some more effort into actually thanking you. So thanks a lot for that :)
