### ISSUE TITLE
Links opened in a new tab from a container tab are opened in non-container tabs

### ISSUE THREAD

**Issue by tokoyami** [akhodakivskiy/VimFx#877] opened 2017-03-25 21:11 UTC
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.10
Firefox version: Nightly 55.0a1 (20170325110246)
OS: Linux
Keyboard language: us
Example URL (if any): 

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [ ] A question
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Open a page in a [container tab](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers)
2. Open any link from the page in a new tab using <kbd>F</kbd>/<kbd>et</kbd>/<kbd>ew</kbd>/<kbd>ep</kbd> or similar.

Expected result: The new tab is opened in the same container as the tab from which the link was triggered.  This is the Firefox behavior when opening a link with the <kbd>Ctrl</kbd> + left mouse button combination or with the middle mouse button.

Actual result: The new tab is opened in a non-container tab.

**Comment by lydell** [comment] 2017-03-25 21:27
Thanks for the issue!

Nothing will be done here though until it is on by default in Firefox Developer Edition.

**Comment by ClonedOne** [comment] 2017-07-19 18:37
Since the issue is still open, I'll just add that now following a lnk in the same tab or a new tab is working as expected. Following the link in a new window will not open it in the container though.

**Comment by lydell** [comment] 2017-08-25 12:36
Closing since this won't be fixed.

**Closed by lydell** 2017-08-25 12:36 UTC
Labels: waiting
