### ISSUE TITLE
Scrolling goes way too far (one keypress = 3x scroll)

### ISSUE THREAD

**Issue by mauke** [akhodakivskiy/VimFx#748] opened 2016-06-04 06:57 UTC
Steps to reproduce:

1. go to https://addons.mozilla.org/en-US/firefox/addon/vimfx/ 
2. hit <kbd>Ctrl+f</kbd> (scroll a whole page down).

Expected result:
After step 1, the last visible line on my screen is "\* Modeled after [Vimium](http://vimium.github.io/) for Chrome." After hitting <kbd>PgDn</kbd> it becomes the first line. This is also what I expect from <kbd>Ctrl+f</kbd>.

Actual result: 
The page is scrolled all the way down to the end. After expanding the "Developer's Comments" and "Version Information" sections and trying again, I can see that a single <kbd>Ctrl+f</kbd> takes me from the top of the page down to "Part of these collections" (equivalent to hitting <kbd>PgDn</kbd> three times).

Similarly, starting at the top of the page and hitting <kbd>Down</kbd> moves the "search for add-ons" box to the top of the screen. But <kbd>j</kbd> takes me to "by [akhodakivskiy](https://addons.mozilla.org/en-US/firefox/user/akhodakivskiy/), [lydell](https://addons.mozilla.org/en-US/firefox/user/lydell/)" (equivalent to hitting <kbd>Down</kbd> three times).

And remapping <kbd>Ctrl+f</kbd> to scroll half a page makes it go 1.5 pages (factor 3 again).

VimFx version: 0.16.1
Firefox version: 46.0.1
OS: Windows 7
Keyboard language: en_US (with some customizations around <kbd>AltGr</kbd>)
Worked before: 
Example URL(s):

**Comment by mauke** [comment] 2016-06-04 07:20
I can't reproduce it anymore; see https://github.com/akhodakivskiy/VimFx/issues/749#issuecomment-223741421.

**Comment by mauke** [comment] 2016-06-04 11:28
I'm not sure what happened, but the issue is back. I changed nothing in my add-ons.

**Comment by lydell** [comment] 2016-06-05 10:15
Thanks for your very clear report, but I can't reproduce.

VimFx version: 0.16.1
Firefox version: 46.0.1, with a new Firefox profile
OS: Ubuntu 16.04
Keyboard language: en_US

> hit <kbd>Ctrl+f</kbd> (scroll a whole page down).

`<c-f>` is not a standard VimFx command. Perhaps you have some other add-on that confuses you?

**Comment by lydell** [comment] 2016-06-09 14:07
> I changed nothing in my add-ons.

Since nobody else seems to experience this, it sounds like an extension conflict. Please test in a new Firefox profile.

**Comment by lydell** [comment] 2016-06-11 07:16
Closing until response.

**Closed by lydell** 2016-06-11 07:16 UTC
