### ISSUE TITLE
Scroll up/down and page up/down do not work in Gmail or Google Groups

### ISSUE THREAD

**Issue by abastardi** [akhodakivskiy/VimFx#592] opened 2015-11-11 04:39 UTC
In Gmail and Google Groups, hitting j/k to scroll or \<space>/\<s-space> to page up or down has no effect (though using the arrow keys and page-up/page-down keys works fine).

**Comment by lydell** [comment] 2015-11-11 05:59
Duplicate of #585.

**Closed by lydell** 2015-11-11 05:59 UTC
