### ISSUE TITLE
Allow to passthrough specific keys per site

### ISSUE THREAD

**Issue by iven** [akhodakivskiy/VimFx#611] opened 2015-11-14 12:55 UTC
In pentadactyl, we can use `passkeys` option to config which keys to passthrough in specific site, like so:

```
set passkeys+=mail.google.com:jkehHI%<CR>,gi,*a
set passkeys+=feedly.com/:jkorv/,ga,gg
```

Could we add this feature to VimFx?

**Comment by lydell** [comment] 2015-11-14 13:02
Duplicate of #255.

Since VimFx 0.6.0, disabling certain commands on certain sites is supported. This is done by using [`vimfx.addKeyOverrides`](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/api.md#vimfxaddkeyoverridesrules) in a [config file](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md).

**Closed by lydell** 2015-11-14 13:02 UTC
