### ISSUE TITLE
Pointer not being released when closing tab that had lock

### ISSUE THREAD

**Issue by SlaughterDog** [akhodakivskiy/VimFx#835] opened 2016-11-16 20:18 UTC
- [x] I've searched for duplicates – also closed issues
- [ ] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.3
Firefox version: 49.0.2
OS: Ubuntu 
Keyboard language: US
Example URL (if any): 

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Visit http://mdn.github.io/pointer-lock-demo/
2. Click canvas
3. Allow mouse pointer capture
4. Use VimFX to close tab

Expected result: Pointer is released, as it would be with ctrl+w

Actual result: Pointer becomes visible but does not get released until quitting Firefox.

**Comment by lydell** [comment] 2016-11-16 20:48
Thanks for your report!

When using the exact same setup as you, I can reproduce the issue.

However, when trying in Firefox Developer edition, I could not. I guess the pointer lock implementation has been improved since Firefox 49.

So it seems like all we need to do is to wait for Firefox 51. If we’re lucky, it’s fixed already in Firefox 50, but I haven’t bothered testing that version.

(It’d be awesome if you could confirm that the problem does not occur in a newer Firefox version!)

**Comment by cesalazar** [comment] 2016-11-18 20:54
I can confirm this issue is present in FF 50. If VimFx is disabled the pointer is released when the tab is closed using Cmd+W

VimFx version: 0.20.4
Firefox version: 50.0
OS: OS X 10.11.6
Keyboard language: US

**Comment by lydell** [comment] 2016-11-19 08:33
Thanks, @cesalazar! Then I guess we'll just wait for Firefox 51, then.

**Comment by d125q** [comment] 2017-01-28 18:20
Firefox 51 is here, and I cannot reproduce the issue.

**Comment by lydell** [comment] 2017-01-28 19:46
@d125q Thanks for the reminder! I’ll close this, then.

**Closed by lydell** 2017-01-28 19:46 UTC
Labels: waiting
