### ISSUE TITLE
seems not support HTML <img> usemap Attribute 

### ISSUE THREAD

**Issue by seaspeak** [akhodakivskiy/VimFx#829] opened 2016-10-31 20:07 UTC
<img> usemap is a practical use, a standard. It's still defined in HTML5. _see_ https://dev.w3.org/html5/spec-preview/image-maps.html
http://stackoverflow.com/questions/5249502/are-html-image-maps-still-used

- [x] I've searched for duplicates – also closed issues
- [ ] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [ ] I've provided the below details:

VimFx version: 0.20.3
Firefox version: 49.0.2
OS: Windows10
Keyboard language: En
Example URL (if any): http://ever-transmission.com.tw/

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [x] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [ ] Something else

Steps to reproduce:

1. Go to http://ever-transmission.com.tw/
2. Press `f`.

Expected result: There should be hint marker for the planets.

Actual result:  There is no hint marker for the planets

**Comment by lydell** [comment] 2016-10-31 20:14
Duplicate of #828.

**Closed by lydell** 2016-10-31 20:14 UTC
