### ISSUE TITLE
0.6.1 is buggy with non-typical keyboard layouts

### ISSUE THREAD

**Issue by NSUSpray** [akhodakivskiy/VimFx#601] opened 2015-11-11 21:28 UTC
I have two non-typical keyboard layouts (Windows XP): modified english and russian (see attached image):
![layout](https://cloud.githubusercontent.com/assets/15806293/11102591/e5295a46-88d6-11e5-8963-4651c3799bd4.png)
Earlier I used keys “1” and “2” (at top row of numerical keys) for going to left or right tab (I put “!” and “"” in appropriate config fields) and with previous version of VimFx it’s worked. But after update to 0.6.1 this shortcuts hasn’t work (with “1” and “2” keys hasn’t work too). If I will toggle on “Ignore keyboard layout” and puts in fields “!” and “"”, then it will work, but then all other shortcuts will hot work in russian layout.
P. S. Also in new 0.6.1 moving current tab not work correctly, with any keys.

**Comment by lydell** [comment] 2015-11-12 06:56
1. Update to VimFx 0.6.2.
2. Enable "Ignore keyboard layout" since you use more than one layout.
3. In the text inputs where you customize keyboard shortcuts,  put only the characters that pressing the desired keys would produce when using the standard en-US QWERTY layout (switch to it temporarily if you're unsure), and nothing else (_not_ any characters that _happened_ to work in VimFx 0.5.x.)

   Also, when having focused one of the customization text inputs, press `<c-q>` before each desired key press. That inserts the correct key notation you're looking for.

**Comment by NSUSpray** [comment] 2015-11-12 08:15
Thanks, now it works!
But moving of tabs is still buggy — tab jumps to the wrong position.

**Comment by lydell** [comment] 2015-11-12 08:37
Please give steps to reproduce. "tab jumps to the wrong position" does not help.

**Comment by NSUSpray** [comment] 2015-11-12 10:11
> But moving of tabs is still buggy — tab jumps to the wrong position.
> Please give steps to reproduce.
![vimfx-moving-tab-bug](https://cloud.githubusercontent.com/assets/15806293/11115746/2152b768-8947-11e5-9953-2f05f8d08300.gif)

**Comment by lydell** [comment] 2015-11-12 11:21
Thanks! Looks like you’re using tab groups, which makes it a duplicate of #462.

**Closed by lydell** 2015-11-12 11:21 UTC
