### ISSUE TITLE
Disable Scroll Delay?

### ISSUE THREAD

**Issue by hackel** [akhodakivskiy/VimFx#830] opened 2016-11-02 18:47 UTC
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.3
Firefox version: 51.0a2
OS: Ubuntu 16.10
Keyboard language: English (international AltGr dead keys)

This is … (pick one!)
- [x] A feature request

When scrolling the page with j/k, there is an initial keyboard repeat delay after scrolling one line, before smooth scrolling starts.  I would like a way to disable this.  I can change the repeat delay in my OS settings, but that does it for any text input as well, which I definitely don't want.

**Comment by lydell** [comment] 2016-11-02 19:43
Duplicate of #811.

**Closed by lydell** 2016-11-02 19:43 UTC
