### ISSUE TITLE
Going 'back' doesn't work

### ISSUE THREAD

**Issue by DavidVentura** [akhodakivskiy/VimFx#618] opened 2015-11-18 20:12 UTC
Hi. I can't navigate backwards/forwards with my keyboard layout, to type "[" or "]" I must press shift-{, and it doesn't seem to work. Pressing mouse4/5 does go backwards/forwards so it's exclusively something to do with the addon/layout

**Comment by lydell** [comment] 2015-11-18 20:16
Duplicate of #563.

**Closed by lydell** 2015-11-18 20:16 UTC

**Comment by DavidVentura** [comment] 2015-11-19 04:12
You are right. This plugin is awesome, thanks
