### ISSUE TITLE
Add support for 'T' Vimium command (tab selector)

### ISSUE THREAD

**Issue by 3v1n0** [akhodakivskiy/VimFx#540] opened 2015-09-30 23:17 UTC
It would be very nice if it would be implemented the Tab selector as Vimium has when pressing Shift+t, you can see what you mean at https://youtu.be/t67Sn0RGK54?t=99

PS: this is already an awesome extension, so keep up the good work!

**Comment by lydell** [comment] 2015-10-01 05:13
Duplicate of #420.

**Closed by lydell** 2015-10-01 05:13 UTC

**Comment by edrex** [comment] 2016-01-26 23:25
I'd like to revisit this. #420 was informative and helpful, but the % prefix isn't very discoverable, and takes 6 keystrokes on top of the filter term (`o` `Shift-%` `Space`, type term, `Tab` once to select first result, `Enter` to activate).

I switch tabs a lot. I hate doing it by list traversal, because I usually have 20+ tabs open. This is the biggest pain point for me (literally pain, cuz RSI :D )

Proposal: `T => o % Space`, which cuts the extra strokes to just `Shift-t` `Tab` `Enter`. This is really close to Vimium's behavior.

I also wonder if there is a Firefox pref to avoid the need to tab down to the first result.

**Comment by edrex** [comment] 2016-01-26 23:35
For reference: It doesn't look like there's an about:config option to have enter select the first result, but there's an addon that does the trick:

https://addons.mozilla.org/en-US/firefox/addon/enter-selects/

**Comment by lydell** [comment] 2016-01-27 06:11
@edrex you can adapt this example: https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#search-bookmarks

Also, thanks for the tip about that extension.

**Comment by edrex** [comment] 2016-01-27 16:34
@lydell would you be open to a patch to add a `T`: "search tabs" command as default?

**Comment by lydell** [comment] 2016-01-27 17:03
No.

**Comment by edrex** [comment] 2016-01-27 19:14
That's unfortunate. I think there is a significant portion of the user base
that is being underserved here.

**Comment by edrex** [comment] 2016-01-27 19:37
But thanks for the support, and I'll be sure to update the wiki with the custom command

**Comment by lydell** [comment] 2016-01-27 19:59
No need to update the wiki when you're basically change one single character.

**Comment by edrex** [comment] 2016-01-28 22:21
It would be more than a single character since my hope (APIs willing) is to borrow the "first suggest result focusing" from the addon above to make the sequence of keystrokes exactly match Vimium (T search <Enter>)

**Comment by betoharres** [comment] 2016-04-08 00:26
+1
