### ISSUE TITLE
Can't use VimFx with Beyond Australis 

### ISSUE THREAD

**Issue by geimerus** [akhodakivskiy/VimFx#679] opened 2016-01-26 09:38 UTC
Hi,

I'm using Beyond Australis 1.3.4.1 and VimFx

When I launching my browser I can't use hotkeys from VimFx in first tab. When I close first tab or open another tab it works. When I open new window I'm again can't use VimFx. I need to create another tab. Even when I create a new tab I can't use VimFx in first tab. VimFx works well when I disable Beyond Australis. I will tell about this issue to creator of Beyond Australis, too.

Thank you for your great extension!

Evgeniy

**Comment by Quicksaver** [comment] 2016-01-26 10:57
(I'm the developer of Beyond Australis.) I tried looking into this but couldn't get VimFX to initialize properly, it threw an error in the console about uri-match(...) being null (bootstrap.js line 51). Happy to debug. :)

**Comment by lydell** [comment] 2016-01-26 16:10
Duplicate of #624.

@Quicksaver Did you install from AMO?

**Closed by lydell** 2016-01-26 16:10 UTC

**Comment by Quicksaver** [comment] 2016-01-26 16:13
Yeah, version 0.11.0.

**Comment by lydell** [comment] 2016-01-26 16:14
In a clean profile? Firefox version?

**Comment by Quicksaver** [comment] 2016-01-26 16:16
Tried in 43 and 47, but on my main developer profile. I was planning on debugging it later (maybe tomorrow) once I finish something else I'm working on. I'll post on the other issue when I know something more.

**Comment by lydell** [comment] 2016-01-26 19:13
@Quicksaver Regarding your “uri.match(...) being null” issue, I think I’ve fixed it on the develop branch. Also, I noticed that when VimFx tried to insert its toolbar button when Beyond Australis is installed, and error was thrown. That’s also fixed on the develop branch. So be sure to be [build VimFx](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/tools.md) from the develop branch when debugging :)

**Comment by Quicksaver** [comment] 2016-01-26 20:19
Is there any chance that you would upload an xpi of that branch, so that I can take a look at it still today? :) Node.js refuses to run on this computer, so otherwise I'll have to build it on another computer, and I won't be able to do that before tomorrow at the earliest.

**Comment by lydell** [comment] 2016-01-26 21:21
Good news: I managed to reduce the problem, so you don’t even have to install VimFx.

1. Download the ultra minimal extension boilerplate here: https://github.com/lydell/VimFx-config/

2. In bootstrap.js, replace the `startup()` and the `shutdown()` functions with this:

   ```js
   function startup() {
     Cu.import('resource://gre/modules/Services.jsm')
     Cu.import('resource://gre/modules/devtools/Console.jsm')
     let mm = Cc['@mozilla.org/globalmessagemanager;1']
       .getService(Ci.nsIMessageListenerManager)
     mm.addMessageListener('VimFx-config:tabCreated', listener)
     mm.loadFrameScript('chrome://vimfx-config/content/frame.js', true)
   }
   function shutdown() {
     let mm = Cc['@mozilla.org/globalmessagemanager;1']
       .getService(Ci.nsIMessageListenerManager)
     mm.removeMessageListener('VimFx-config:tabCreated', listener)
     mm.removeDelayedFrameScript('chrome://vimfx-config/content/frame.js')
   }
   function listener() {
     console.log('A new frame script says hello!')
     return Date()
   }
   ```

3. In frame.js add this:

   ```js
   let [message] = sendSyncMessage('VimFx-config:tabCreated')
   console.log('New frame script received message:', message)
   ```

4. Install the extension.

5. Note how something like the following is logged to the console for each open
   tab:

   ```
   A new frame script says hello!
   New frame script received message: Tue Jan 26 2016 22:13:11 GMT+0100 (CET)
   ```

6. Open a new tab or window and note how _two_ messages like the above are
   logged per new tab.

7. Install Beyond Australis.

8. The test extension should still work like expected.

9. Disable and re-enable the test extension.

10. Open a new window. Note how only _one_ message is now logged, followed by:

    ```
    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage]
    ```

(You might need to restart Firefox at some point, but I don’t think so.)

**Comment by lydell** [comment] 2016-01-26 21:54
Yet some good news: I fixed the issue in the develop branch by switching from a sync message to an async message.

@Quicksaver You might still want to look into why your add-on breaks the sync messaging, as that could conflict with other add-ons as well, but that’s up to you :)

**Comment by Quicksaver** [comment] 2016-01-26 23:03
That is awesome! Thanks for your work! :)

I tried your boilerplate build you posted, and could indeed reproduce it like you mentioned with the latest release of Beyond Australis, but I couldn't reproduce it with my local build. It does have a ton of changes where it comes to messages to frame scripts, but I have absolutely no idea why it was breaking your syncMessage before or what exact change fixed it...

Oh well. :) Either way, it's probably better this way, it's fixed on Beyond Australis for other possible similar conflicts, and it's probably better for VimFX to use async messaging anyway. Guess everybody ended up winning here.

**Comment by lydell** [comment] 2016-01-27 06:14
Yay! Good to hear! (And if somebody is especially interested in what was going on (s)he might be able to find out via `git bisect`...)
