### ISSUE TITLE
UI too big

### ISSUE THREAD

**Issue by ibabushkin** [akhodakivskiy/VimFx#575] opened 2015-11-09 22:42 UTC
On VimFX 0.6, Firefox 42.0, on Arch Linux, I managed (by accidental keystrokes) to break the visual appearance of VimFX. URL hints and the help dialog brought up by `?` are more than twice the size and look blurry (due to the size I assume). Reinstalling VimFX and/or Firefox did not solve the issue. I could not find any information in the docs and can't find a way to reproduce/recover this problem.

Thanks for your time

**Comment by lydell** [comment] 2015-11-10 06:05
I don't understand.

Was it correctly sized from the beginning?

Then all of a sudden you got the issue?

And now it's fine again?

**Comment by ibabushkin** [comment] 2015-11-10 08:01
1) Yes, the UI was "right-sized" during my whole usage-span of VimFX, until yesterday.
2) No, I could not fix the problem, sorry for the blurry description. What I meant was that I could not find out what exactly caused the issue in the first place.

**Comment by eush77** [comment] 2015-11-10 08:18
Maybe it was VimFX update? I also noticed that link hints look a little different now.

**Comment by ibabushkin** [comment] 2015-11-10 08:31
Well, that's certainly possible. But afaik an update get's activated after a browser restart, which I did not perform just before the issue appeared.

**Comment by lydell** [comment] 2015-11-10 08:41
@ibabushkin 

> 1) Yes, the UI was "right-sized" during my whole usage-span of VimFX, until yesterday.

Sorry, I meant if it looked right in version 0.6.0 for a while.

Could you post a screen shot?

> afaik an update get's activated after a browser restart

Nope, VimFx is a so-called restartless add-on.

@eush77 

> Maybe it was VimFX update?

VimFx 0.6.0 is still the latest version, so, no.

> I also noticed that link hints look a little different now.

Yes they do, and that's intentional. #574 mentions it a bit.

**Comment by JDongian** [comment] 2015-11-10 15:45
Getting the same issue on Arch as of today.
![herp](https://cloud.githubusercontent.com/assets/3201248/11066868/45af15f6-880d-11e5-8f16-b3d2a72e2082.png)

the issue isn't blurry text for me (wtf?), but rather there's a persistent text shadow applied to all the text used by vimFx.

**Comment by JDongian** [comment] 2015-11-10 15:47
More screenshot:
![herp](https://cloud.githubusercontent.com/assets/3201248/11066986/bb25468e-880d-11e5-9d9b-4f478fa3ed7b.png)

**Comment by lydell** [comment] 2015-11-10 16:00
That does not look too big to me. Are you sure that you’ve seen the help dialog of version 0.6.0 with smaller text? Perhaps you had a smaller window the first time—the text size adjust based on the area available.

It does seem that you are experiencing #574, though.

However, if you still consider the text size too large, you can use custom [styling](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/styling.md) to make it smaller. However, then you loose the dynamic resizing, which you might like if you sometimes use a smaller window. If so, we could turn the hard-coded maximum font size of 20px into an about:config-only pref.

**Comment by JDongian** [comment] 2015-11-10 16:13
I don't have a problem with the size, but it used to be smaller before. Thanks for the styling link -- that should provide me a quickfix.

**Comment by ibabushkin** [comment] 2015-11-10 19:35
First of all, thanks for your replies guys. Second, it seems that the hints look the same as in the screenshots provided by @JDongian. If this is intentional, ok, otherwise the guess that the problem might be on the Arch side of things is worth a closer look, since I had to tweak the font settings after installing a GUI.

**Comment by lydell** [comment] 2015-11-11 11:34
@ibabushkin I'm closing this since you do not seem to want to change the default or see the need of more options.

**Closed by lydell** 2015-11-11 11:34 UTC
Labels: unconfirmed

**Comment by ibabushkin** [comment] 2015-11-11 22:06
@lydell Yeah, I am trying to tweak it now, seems like it is wanted/expected behaviour after all :)
