### ISSUE TITLE
String.fromCharCode() doesn't return the right character in special keyboard.

### ISSUE THREAD

**Issue by JonathanDaSilva** [akhodakivskiy/VimFx#431] opened 2015-01-04 15:57 UTC
Hi everyone.
All is in the title I can't use the extension because of my personnalize keyboard. Let me explain a little, I'm french so I have an AZERTY keyboard, but I have a personnalize layout of the BEPO Keyboard.
http://bepo.fr/wiki/Accueil

Basically, if I press the "B" letter (BEPO) I have an "A".

I have look at the code and it seemns realy easy to fix that. Actualy you are using the keyCode and convert it to the character with String.fromCharCode. 

![Demonstration](http://goo.gl/i89Z7R)

I have never done an firefox so I don't know If you have the key attribut on the event.

I'm on windows I don't know if the same problème occur on other plateform.

I look forward your suggestion.

Best Regards Jonathan Da Silva.

**Comment by lydell** [comment] 2015-01-04 16:24
Duplicate of #249.

**Closed by lydell** 2015-01-04 16:24 UTC
