### ISSUE TITLE
VimFX might be causing "ghost windows" (memory leaks)

### ISSUE THREAD

**Issue by CongeeCafe** [akhodakivskiy/VimFx#664] opened 2016-01-09 21:54 UTC
Recently I noticed Firefox was getting very sluggish after being opened for a long time. After going through my addons, it seems VimFx might be the cause.

With all addons disabled, I went to Google maps and zoomed/panned around until the memory usage stabilized around 450MB. I then ran a memory report in about:memory and google.com/maps showed up as an active window under `window-objects`. When the maps tab is closed, the corresponding entry in about:memory disappears within a minute and the memory usage drops to 350MB.

With only VimFx enabled, I used the same test, but when I close the Google maps tab, its entry in about:memory never disappears. Eventually, the entry is categorized under `top(none)/ghost` in the `window-objects` group. The tab is also listed under the `ghost-windows` category and the memory usage never drops.

Config: VimFx 0.10.0, Firefox 43.0.4 on Windows

**Comment by d125q** [comment] 2016-01-10 00:48
Same issue here, Firefox 43.0.4 on ArchLinux.  I am glad I am not the only one experiencing this.

**Comment by lydell** [comment] 2016-01-10 06:23
Does the ghost window disappear if you close another tab after closing the Google Maps tab?

**Comment by lydell** [comment] 2016-01-10 09:07
I just tried this with:

- Trisquel 7
- Firefox 41.0.2 as well as Firefox 46.0a1 with multi-process turned on and off
- VimFx 0.10.0 as well as latest master
- Completely new Firefox profiles

This is exactly what I did:

1. Opened about:memory.
2. Opened maps.google.com in a new tab.
3. Zoomed and panned around, switched between map and Earth mode and used Street View for a while.
4. Closed the Google Maps tab (by clicking the “x” icon on its tab using the mouse).
5. Pressed the “Measure” button in the about:memory tab.
6. Searched for “maps” in the tab. I could then find references to the Google Maps tab.
7. After a short time, say, around 20 seconds, I repeated steps 5 and 6. Then I could not see any references to Google Maps anymore (the garbage collector seems to be done at this point).

At all times I had 0 ghost windows according to about:memory.

Perhaps I’m missing something?

**Comment by d125q** [comment] 2016-01-10 13:32
Memory never goes down.  It happens with regular browsing as well, so it is not exclusive to Google Maps.  I will try to pinpoint the exact cause ASAP.

**Comment by lydell** [comment] 2016-01-10 13:37
(Just to clarify: In my tests memory usage, as measured by gnome-system-monitor _did_ drop.)

**Comment by CongeeCafe** [comment] 2016-01-10 20:24
It seems the memory issue occurs with Google Maps mainly under high stress usage (in my case, searching for directions from A to B, then rapidly panning/zooming until Firefox memory usage peaks around 800MB).

I did some more experimenting and found a more consistent way to reproduce the bug.

1. Launched Firefox with only VimFX enabled.
2. Opened about:memory in the default blank tab.
3. Opened a new tab and went to `youtube.com` (already logged in) and clicked the favourites playlist in the sidebar. When the page finished loading, I closed the tab.
4. Opened another new tab and went to `neowin.net`. I closed the tab after it loaded.
5. Waited 1 minute and ran a memory report. Both tabs were listed under the `ghost` category, and they remained there 2 minutes later:

![ghost1](https://cloud.githubusercontent.com/assets/7608475/12223628/a00777e2-b7aa-11e5-9a3a-46c9354a5a55.png)
![ghost2](https://cloud.githubusercontent.com/assets/7608475/12223630/b085aec2-b7aa-11e5-8301-7a1cff33485f.png)

Next:
6. Disabled VimFX and restarted Firefox.
7. Repeated steps 2-4 and ran a memory report after 30 seconds. No entries for either tab showed up.

Some notes:
- Not all sites cause the tab to leak. Just going to the Youtube homepage will not cause the tab to end up in the ghost category. Similarly, arstechnica.com doesn't either.
- After performing steps 1-5, the youtube entry (and sometimes the neowin entry) drop out of about:memory after ~30 secs of disabling VimFX.

**Comment by lydell** [comment] 2016-01-11 17:31
Thanks for your update @CongeeCafe. Now I can reproduce.

**Closed** 2016-01-11 18:36 UTC
Labels: bug
