### ISSUE TITLE
'F' and 'et' broken in Firefox 126 Developer Edition

### ISSUE THREAD

**Issue by alexnguyennn** [akhodakivskiy/VimFx#1001] opened 2024-05-18 05:47 UTC
Hi there,
Posting as I've recently updated to Firefox Developer Edition 126.0.b9 and noticed 'F' and 'et' no longer allow opening tabs or opening links in VimFx 27.1 while 'f' still follows links as intended - wondered if it was just me and something else in my setup is affecting behaviour.

Anyone else seeing this behaviour?

Thanks in advance.

**Comment by girst** [comment] 2024-05-18 15:46
this seems to be a regression from bug bugzil.la/1742889

thanks for reporting, i'll work on a fix

**Comment by girst** [comment] 2024-05-18 16:24
fixed in v0.27.2. thank you again!

**Closed by girst** 2024-05-18 16:24 UTC

**Comment by alexnguyennn** [comment] 2024-05-19 01:44
thanks for the quick fix, really appreciate it.  i'll give it a go :)
