### ISSUE TITLE
No "reached end of page, continued from top" message during find

### ISSUE THREAD

**Issue by digital-carver** [akhodakivskiy/VimFx#526] opened 2015-08-18 18:59 UTC
Note: I suspect https://github.com/akhodakivskiy/VimFx/issues/390 might fix this automatically (specifically the option to not have Enter close the Find box), but I don't know for sure, so am opening this as a separate issue. 

When using the `n` (or `N`) shortcut key to search for next matches, when the last match of the page has been found, it automatically wraps back to the first match - but without the Firefox default "Reached end of page, continued from top" message. The message is usually displayed in the Find bar itself, which is why I mentioned that #390 might fix this. If it does, please go ahead and unceremoniously close this issue.

**Comment by lydell** [comment] 2015-08-18 19:52
Duplicate of #398 I’d say.

**Closed by lydell** 2015-08-18 19:52 UTC
