### ISSUE TITLE
navigate with j/k inside of history popup

### ISSUE THREAD

**Issue by pcuinty** [akhodakivskiy/VimFx#857] opened 2017-01-03 13:34 UTC
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.6
Firefox version: 50.1.0
OS: Xubuntu 16.04
Keyboard language: de
Example URL (if any): 

This is 

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [x] A feature request
  - [x] I've given a **detailed** _example_ below
- [ ] Somehting else

When I open the history popup with `gH` I have to navigate with the arrow keys within it. I think it should be possible to use `j` and `k` to navigate through the entries.

**Comment by lydell** [comment] 2017-01-03 14:40
Duplicate of #833.

**Closed by lydell** 2017-01-03 14:40 UTC
