### ISSUE TITLE
VimFx destory the native Find.Is possible fix it !?

### ISSUE THREAD

**Issue by ar1xwe** [akhodakivskiy/VimFx#562] opened 2015-11-02 08:28 UTC
After Install VimFx.

It destory the native Find mode even if the user remove the binding of "Begin Find", "Jump to Next Match".

Hope someone can help me out ... It's really important !

**Comment by ar1xwe** [comment] 2015-11-02 08:31
Sorry about the uncompleted describing.

This bug is what if a user entered the "Find" mode.
type some stuff into the find bar, the user can not use "Enter" to navigate to next match.

**Comment by lydell** [comment] 2015-11-02 09:18
Duplicate of #390.

**Closed by lydell** 2015-11-02 09:18 UTC
