### ISSUE TITLE
Option to change hints font

### ISSUE THREAD

**Issue by alectic** [akhodakivskiy/VimFx#581] opened 2015-11-10 14:16 UTC
After the last upgrade the hints font looks blurred and is hard to read. Is it possible to add an option to change the font and its size?

I'm aware of the fact that the font may look different to someone else and it may depends on my font settings and installed fonts, but an option to change it would be great for everyone. The font looked good before. This is the first thing I've noticed about the otherwise silent upgrade.

OS: Arch Linux x64
Firefox: 42.0
VimFx: 0.6.0

![vimfx](https://cloud.githubusercontent.com/assets/6550848/11064408/bdb6d5a4-87c5-11e5-99cc-ab29e7e2f010.png)

**Comment by lydell** [comment] 2015-11-10 14:20
The blurred fonts issue is a duplicate of #574.

The appearance of hint markers can be customized through custom [styling](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/styling.md).

**Closed by lydell** 2015-11-10 14:20 UTC

**Comment by alectic** [comment] 2015-11-10 14:30
@lydel darn, I've looked at the issues and didn't see it. Styling it will do for me, but in my opinion an option would still make it easier and friendlier.

**Comment by alectic** [comment] 2015-11-10 14:38
@lydell after reading the discussion in the issue you referenced, I disabled the theme I was using and the hints font looks good and clear again.
