### ISSUE TITLE
Shortcuts for new windows (regular and private)

### ISSUE THREAD

**Issue by sumit0190** [akhodakivskiy/VimFx#493] opened 2015-05-25 23:48 UTC
I do not know whether shortcuts for new windows is outside the scope of this plugin, seeing how there are absolutely no keybindings (at present) for window management. I personally work a lot with multiple windows (both regular and private), and so on my local fork of VimFx I have successfully added these shortcuts. Any chance these will be included in later versions? Or do you want me to submit a pull request instead?

**Comment by lydell** [comment] 2015-05-26 05:50
You can submit a PR if you feel like it, but don't bother to polish it first. I'd just like to get a feel for what exactly you have in mind and what it looks like in code.

This weekend I almost finished a refactor that among other things will allow other add-ons to extend VimFx. So perhaps it'd make sense to have these window mappings in a separate add-on. Either way the refactor will give your PR merge conflicts.

Lastly, this is a duplicate of #402 so I'm going to close this one, but feel free to continue commenting here.

**Closed** 2015-05-26 05:51 UTC

**Comment by sumit0190** [comment] 2015-05-26 12:07
I understand your concerns about needlessly adding new mappings to the base extension, and dealing with it by making your plugin extensible instead. 

I do not know if this is the appropriate way of doing this, but on my local fork of VimFx I simply added keybindings for regular and private windows in the 'defaults' file, and then made changes in the 'commands' file corresponding to those keybindings. In my case, it was as simple as calling a high level API (OpenBrowserWindow, similar to BrowserOpenTab). I then made corresponding changes to the help and localization files. I feel that for such relatively simple additions, the ones which already have high-level APIs waiting to be called, it wouldn't make a lot of sense to make separate add-ons. Then again, that's just me.

**Comment by lydell** [comment] 2015-05-26 14:06
What you say makes a lot of sense. We should add a Windows category in addition to the Tabs category.

**Comment by lydell** [comment] 2015-05-26 14:17
The hardest thing, IMO, is default keybindings. Could you post a suggestion?

**Comment by sumit0190** [comment] 2015-05-26 14:25
Yes, I coming up with intuitive keybindings might be tough. The ones that I am personally using right now are:
w - New Window
wp - New Private Window
Q - Close Window
I know, I know - these are aren't all that practical, but they get the job done for me.

**Comment by lydell** [comment] 2015-05-26 14:28
w and wp conflict with each other.

**Comment by sumit0190** [comment] 2015-05-26 14:50
Yes, they do. I work around it by assigning 'B' for the private window, but that's not very practical. In any case, the keybindings are completely customizable by the user, right? We can just give them this functionality, and leave it upto them to map it as per their workflow. This doesn't mean we shouldn't try to come up with good keybindings, it just means that we shouldn't put waayyy too much thought into it (especially at this point, when we are still testing the functionality). Wouldn't you agree?

**Comment by lydell** [comment] 2015-05-26 15:11
All commands must have reasonable defaults.

**Comment by sumit0190** [comment] 2015-05-26 23:59
Well, maybe we can use 'W' for private windows and 'w' for regular ones (or vice versa). 'Q' would work fine on either. I think those are the most commonly used operations with windows, but I could be wrong.

**Comment by lydell** [comment] 2015-05-27 05:54
I think it is better to continue the discussion in #402 now.
