### ISSUE TITLE
numbers + string search-based hints

### ISSUE THREAD

**Issue by lc-guy** [akhodakivskiy/VimFx#559] opened 2015-10-27 20:07 UTC
it would be nice if an alternative to the current letters method to hinting would be using numbers and allowing the user to enter a string: if the string matches a link, that link would be used, similar to how vimperator works.

For example, if there's a "Download link" and a "contribute" link on a page, typing f  + 'd' would open the first link. If there was a "download link" and "downtime" link on a page, typing f + 'load' would do the same.

**Comment by lydell** [comment] 2015-10-27 20:54
Even if not _exactly_ the same, I’d say this is a duplicate of #340. It was closed because of “too little interest”. Feel free to continue the discussion there. But in the near future there are no plans for another hints mode. However, do you know about the built-in Firefox feature [find – links only](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/handy-standard-firefox-features.md#findlinks-only)?

**Closed by lydell** 2015-10-27 20:54 UTC
