### ISSUE TITLE
Closing pinned tab not working

### ISSUE THREAD

**Issue by mesuutt** [akhodakivskiy/VimFx#805] opened 2016-09-03 13:27 UTC
Pressing `x` key for close tab on the pinned tab not working.

**Comment by lydell** [comment] 2016-09-03 13:37
Correct. Neither does Firefox's default shortcut for closing tabs, `<c-w>`. This is by design.

**Closed by lydell** 2016-09-03 13:37 UTC

**Comment by mesuutt** [comment] 2016-09-19 13:22
Ok then why closing not pinned tabs with pressing `x` exist ?
I am using `x` instead `<c-w>` for close tabs and I want to close pinned tabs with `x` also. How can I do this?

**Comment by zachthompson** [comment] 2016-11-27 23:23
Ran into this as well.  What about listing "gpx" in the shortcuts? Or do you not want to get into combinations of commands?
