### ISSUE TITLE
Shortcut to focus the biggest scrollable element

### ISSUE THREAD

**Issue by loonies** [akhodakivskiy/VimFx#641] opened 2015-12-07 09:15 UTC
Sometimes it's not possible to scroll a page unless the biggest element is focused using `zf`.

Instead of using `zf` followed by a hint marker, add a shortcut that will focus the biggest scrollable element.

Shortcut candidate: `gz`

**Comment by lydell** [comment] 2015-12-07 09:58
Duplicate of #633.

**Closed by lydell** 2015-12-07 09:58 UTC
