### ISSUE TITLE
Escape is not working with "ignore keyboard layout"

### ISSUE THREAD

**Issue by prodik** [akhodakivskiy/VimFx#741] opened 2016-05-27 18:29 UTC
Steps to reproduce:

1.  Turn on the "Ignore keyboard layout" option
2.  Press "o" or "F6" on any page
3.  Try to remove focus from the address bar with escape

Expected result: The focus is removed

Actual result: Escape just highlights a text in the address bar just as if vimfx is not installed.

VimFx version: 0.15.1
Firefox version: 0.46.0.1
OS: Debian Linux
Keyboard language: ru
Worked before: never tried before
Example URL(s): any

**Comment by lydell** [comment] 2016-05-28 09:01
I cannot reproduce.

VimFx version: 0.15.1
Firefox version: 0.46.0.1, with a new Firefox profile
OS: Ubuntu 16.04
Keyboard language: en, sv, ru (`setxkbmap ru`)

The `m` command can be (ab)used to understand what VimFx interprets a keystroke as. Please press `m` (rebind it if needed) and then `<escape>`. What does the notification say?

When I do so, I get a notification saying `Mark set: <escape>`, regardless of the "Ignore leyboard layout" option and regardless of keyboard layout/language.

Closing until more information is provided.

**Closed by lydell** 2016-05-28 09:01 UTC

**Comment by prodik** [comment] 2016-05-28 10:56
It says "Mark set: <Caps lock>", cause
setxkbmap -option caps:swapescape is set.
I think that is the source of a problem.

**Comment by lydell** [comment] 2016-05-28 11:48
Then simply replace `<escape>` with `<capslock>` in all VimFx shortcuts (or add `<capslock>` as alternatives to `<escape>`).

Alternatively, add the following to a [config file](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md):

```js
vimfx.set('translations', {
  'CapsLock': 'Escape',
})
```

There's nothing more VimFx can do.

Let me know if the above works for you! :)

**Comment by lydell** [comment] 2016-05-29 06:08
> There's nothing more VimFx can do.

Thinking about it some more, there’s nothing more VimFx even _should_ do if possible. You asked VimFx to ignore your keyboard layout (which changes `<capslock>` into `<escape>`). And it does. As said, the way to go is to either add `<capslock>` to shortcuts, or translate `CapsLock` into `Escape`.
