### ISSUE TITLE
No Hint Markers for Latest Videos on cinemassacre.com

### ISSUE THREAD

**Issue by darvelo** [akhodakivskiy/VimFx#617] opened 2015-11-17 05:43 UTC
On http://cinemassacre.com/, hint markers are not generated for the "Latest Videos" section in the middle of the page.

VimFx: 0.6.2

**Comment by lydell** [comment] 2015-11-17 07:47
This is caused by the same bug as in #584, which has been fixed, so I'm closing this. Thanks for your report!

**Closed by lydell** 2015-11-17 07:47 UTC
