### ISSUE TITLE
Allow to customize shortcuts per website.

### ISSUE THREAD

**Issue by ypid** [akhodakivskiy/VimFx#539] opened 2015-09-28 20:48 UTC
Hi

I guess most of us spend some time on github.com :smile: and some of you probably already noticed the shortcuts which can be used on github.com (use `?` with VimFx disabled to see them). The problem is that with VimFx enabled on github.com most of the github shortcuts will be handled by VimFx by default. One possible solution to this could be to allow to overwrite the global shortcuts of VimFx with per website shortcuts/disabled shortcuts.

This issue is not very high priority because I mostly use the `y` on github and disabled all commands prefixed with `y` in VimFx for now because I don’t really use them yet.

**Comment by lydell** [comment] 2015-09-28 20:53
Duplicate of #255.

In the development version there's also the `I` command which is handy in some cases. For example, when I want to use the `y` shortcut on github, I press `Iy`.

**Closed by lydell** 2015-09-28 20:53 UTC

**Comment by ypid** [comment] 2015-09-28 20:57
Thanks for the hint. Sounds interesting …
