### ISSUE TITLE
When you scroll with the arrow keys, it may reverse scrolling.

### ISSUE THREAD

**Issue by typetonk2** [akhodakivskiy/VimFx#808] opened 2016-09-12 20:30 UTC
Steps to reproduce:
1. Follow the link on a page.
2. Press up/down arrow keys.

Expected result: 

If you press the up arrow key to scroll up.
If you press the down arrow key to scroll down.

Actual result: 

  After follow the link on the page, when you scroll with arrow key, it may reverse scrolling.

Added information:
- Please check GIF image.
  ![vimfx_reversescroll](https://cloud.githubusercontent.com/assets/1439590/18444485/5cadea78-7954-11e6-9d38-1a7e56ddb819.gif)
- This issue has occurred only if e10s is enabled.

VimFx version: 0.18.1
Firefox version: 48.0.2
OS: Windows 10
Keyboard language: ja
Worked before: Unsure
Example URL(s): github.com

**Comment by lydell** [comment] 2016-09-13 07:41
Thank you for your very clear bug report! The GIF image is very much appreciated.

I can reproduce this in Firefox Developer Edition 50.0a2 (2016-09-12), but it seems to be a Firefox bug, because I can trigger the same behavior with on test page without VimFx:

```html
<!doctype html>
<meta charset="utf-8">
<title>Firefox scrolling bug demo</title>
<ol>
<li>Press Space (to scroll a page down).
<li>Wait for the JavaScript on this page to smoothly scroll you back to the top.
<li>Press the Down arrow (to scroll a line or so down).
</ol>
<p>Expected behavior: You're smoothly scrolled a line or so down.
<p>Actual behavior: You're smoothly scrolled a line or so down, but but immediately after that bounces back up again.
<p style="margin-top: 150vh">I'm at the bottom!
<script>
const intervalId = window.setInterval(() => {
  if (window.scrollY > 0) {
    document.documentElement.scrollTo({top: 0, behavior: 'smooth'})
    window.clearInterval(intervalId)
  }
}, 1000)
</script>
```

**However,** I can't reproduce the problem in Firefox Nightly 51.0a1 (2016-09-12) – neither with VimFx nor with the above test page. So probably we just have to wait for Firefox 51.

It would be awesome if you could confirm that it does not happen for you in Firefox Nightly as well!

**Comment by typetonk2** [comment] 2016-09-13 14:54
Thank you for response!
I have tried in the Nightly 51.0a1, and as you say this Issue did not happen.
So I wait for the Firefox51, or, will continue to use in the Nightly.

**Comment by lydell** [comment] 2017-01-28 19:47
Closing, since Firefox 51 has been released.

**Closed by lydell** 2017-01-28 19:47 UTC
Labels: waiting
