### ISSUE TITLE
links diplacement when zooming in/out the page

### ISSUE THREAD

**Issue by Zlofey** [akhodakivskiy/VimFx#598] opened 2015-11-11 11:18 UTC
100%
![4](https://cloud.githubusercontent.com/assets/9608821/11089917/3db66b9a-8887-11e5-81df-3351856c1b19.png)

zoomed in
![3](https://cloud.githubusercontent.com/assets/9608821/11089933/5987f2da-8887-11e5-9b3a-84750ec6fa75.png)

**Comment by lydell** [comment] 2015-11-11 11:23
Duplicate of #594. See also #554.

**Closed by lydell** 2015-11-11 11:23 UTC

**Comment by Zlofey** [comment] 2015-11-11 11:36
tnx
