### ISSUE TITLE
VimFx stops working after HUD use on Ubuntu (16.04)

### ISSUE THREAD

**Issue by fprawits** [akhodakivskiy/VimFx#809] opened 2016-09-16 12:12 UTC
Steps to reproduce:

1.  Open Firefox on Ubuntu 16.04
2.  Use Unity's HUD (tap Alt Key) and type anything 
3.  Switch focus back to firefox via mouse click or tapping Alt again

Expected result: 
Behaviour of VimFx should remain unchanged

Actual result: 
VimFx doesn't react to any shortcut any longer, although icon shows it didn't enter Ignore mode.
Pressing Esc also doesn't solve this, so far my workaround is a restart of Firefox. Disabling and Enabling VimFx in the browsers app menu makes VimFx work again until I use it to open a new tab, after that it again refuses to recognize any keyboard activity

Additional information:
e10s is disabled
I have a lot of tabs open (>30), maybe this has to be considered while trying to reproduce this results
The machine I curently have this issue with is a Dell XPS 13 9343 (dev edition)

VimFx version: 0.18.1
Firefox version:  48.0 (48.0+build2-0ubuntu0.16.04.1)
OS: Ubuntu 16.04
Keyboard language: De (German)
Worked before: bug appeared to me random at first, only recently I found out how to reproduce it
Example URL(s): not limited to specific URL

**Comment by lydell** [comment] 2016-09-17 10:23
I downloaded ubuntu-16.04.1-desktop-amd64.iso, put it on a USB stick, booted it, and installed VimFx in the Firefox that comes with it (that’s Firefox 47.0 – I later updated to Firefox 48.0 as well, but it made no difference).

After closing the HUD by clicking on the Firefox window or tapping Alt, I then tried to focus the location bar using `o`. I noticed that:

- Sometimes the location bar was instantly focused as expected.
- Sometimes I had to press `o` one, two or three extra times before anything happened.

I also tried pressing `<c-l>` (the standard Firefox shortcut for focusing the location bar) instead of `o` directly after returning from the HUD. That seemed to always focus the location bar reliably. However, then trying to use `<escape>` to blur it had the same problem as for `o`: Sometimes I had to press `<escape>` several times before anything happened.

**But at no point did I have to restart Firefox to get VimFx working again.**

To be able to debug the problem, I installed [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/). However, in Firefox Developer Edition I couldn’t reproduce the problem. So I downloaded an [unbranded Firefox](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) instead, to try to get a version closer to the Ubuntu default Firefox. Unfortunately, I could not reproduce the problem there either.

So I don’t really know what to do now.

1. Are you sure that you have to restart Firefox to get VimFx working again, or is pressing a key several times enough for you too?
2. Can you reproduce in  a clean profile?
3. Can you reproduce in Firefox Developer Edition or in unbranded Firefox?

**Comment by fprawits** [comment] 2016-09-17 10:55
First of all thanks for the fast reply, I will see to it that I can test as many of your suggestions as possible myself, probably I will even install ubuntu 16.04 on a different machine and see what results I get there. So far I only wanted to add the following to my original post:

a)  The Firefox standard shortcuts are unaffected by this issue, that is: things like ctrl+l (focus adressbar), ctrl +f (find) or Alt + left arrow (go to previous page) are still working after using the HUD

b)  To reliably reproduce the bug, it is absolutely essential that something is actually typed while in the HUD. Simply tapping the Alt key twice to bring up the HUD and make it disappear again will not break VimFx functionality "most" of the time (I can't give an exact number on this, but in the 20-30 times I was reproducing this issue now, VimFx only stopped working twice when bringing up the HUD without actually typing something in it)

c)  For my system right now, it doesn't matter how often I keep pressing the VimFx hotkeys, after using the HUD it won't work until I restart FF again. Please also note that I edited my original post yesterday because I found out that simply disabling/enabling VimFx also doesn't fully resolve the issue.

d)  I mostly test the VimFx functionality with some of the scroll commands ('j', 'k' or 'd'), but since you asked: the 'o' shortcut doesn't work as well (none of the shortcuts does), also pressing Escape after focusing the the adress bar via 'ctrl+l' doesn't blur the focus. It is literally as if VimFx is not installed at all!

**Comment by fprawits** [comment] 2016-09-17 11:20
Just tried out a clean profile, so here is the answer to point 2.:

With a clean profile, VimFx indeed resumes functionality after HUD usage, however this is not depending on the number of key presses, instead a certain amount of time (~2-3 seconds) has to pass before VimFx is wrking again, so during this 2-3 seconds any shortcuts will be ignored!

**Comment by lydell** [comment] 2016-09-17 11:33
Thanks! A few points:

- I tried both typing something into the HUD and closing it immediately without typing. For me, I seemed to get the same results.
- I might have experienced the 2-3 seconds thing as well, but just didn’t realize it.

Also, could you try out Firefox Developer Edition and/or unbranded Firefox?

**Comment by lydell** [comment] 2016-09-17 12:00
I just found out that it _is_ possible to test stuff in regular Firefox – it’s just a bit more tedious.

1. Download [VimFx 0.18.1 with some logging added](https://github.com/akhodakivskiy/VimFx/files/478127/VimFx.zip)
1. Rename the file to `VimFx.xpi`
1. Go to about:debugging
2. Hit the “Load Temporary Add-on”
3. Choose your `VimFx.xpi`
4. Open the Browser Console (`<c-J>`)
5. Press some key in the main Firefox window – you should see stuff being logged in the Browser Console

VimFx ignores your keypresses if it detects that menu popups are open (such as the File menu, or the context menu), so that you can use the accesskeys of menus. This is called `popupPassthrough` in the code (and you can see that word in the logging).

What happens for me is that right after I’ve returned from the HUD, the File, Edit, View, History, Bookmarks, Tools and help menus appear to be open (though it’s not visible). Then, they seem to “close” one after another. _Then,_ VimFx finally “runs” again.

My guess is that in your main profile, some menu appears to be open forever.

Could you please test out and post the logs?

**Comment by fprawits** [comment] 2016-09-17 23:09
Ok so here is what I did:

1. Saved file from your link
2. Renamed the .zip file to .xpi
3. Loaded it as a temporary addon
4. Browser Console Logs of some normal scrolling (everything still fine):

keydown! Object { key: "j", popupPassthrough: false }events.js:61
  consumed keydown Object { suppress: true }events.js:78
keydown! Object { key: "j", popupPassthrough: false }events.js:61
  consumed keydown Object { suppress: true }events.js:78
keydown! Object { key: "k", popupPassthrough: false }events.js:61
  consumed keydown Object { suppress: true }events.js:78
keydown! Object { key: "k", popupPassthrough: false }events.js:61
  consumed keydown Object { suppress: true }events.js:78
keydown! Object { key: "k", popupPassthrough: false }events.js:61
  consumed keydown Object { suppress: true }events.js:78

4. tapping Alt to bring up HUD and type somtehing, tapping Alt to close HUD. Trying to scroll again via "j" or "k" not working any more. Browser Logs:

keydown! Object { key: "Alt", popupPassthrough: false }events.js:61
  consumed keydown Object { suppress: null }events.js:78
Warning: 'nsIOService::NewChannel()' deprecated, please use 'nsIOService::NewChannel2()'Distro.jsm:63:18
  popup is open <menupopup id="menu_EditPopup" onpopupshowing="updateEditUIVisibility()" onpopuphidden="updateEditUIVisibility()" _moz-menupopupstate="open">events.js:297
  popup is open <menupopup id="menu_viewPopup" onpopupshowing="updateCharacterEncodingMenuState();" _moz-menupopupstate="open">events.js:297
  popup is open <menupopup id="goPopup" placespopup="true" oncommand="this.parentNode._placesView._onCommand(event);" onclick="checkForMiddleClick(this, event);" onpopupshowing="if (!this.parentNode._placesView)                                            new HistoryMenu(event);" tooltip="bhTooltip" popupsinherittooltip="true" _moz-menupopupstate="open">events.js:297
  popup is open <menupopup id="bookmarksMenuPopup" placespopup="true" context="placesContext" openInTabs="children" oncommand="BookmarksEventHandler.onCommand(event, this.parentNode._placesView);" onclick="BookmarksEventHandler.onClick(event, this.parentNode._placesView);" onpopupshowing="BookmarkingUI.onMainMenuPopupShowing(event);                                if (!this.parentNode._placesView)                                  new PlacesMenu(event, 'place:folder=BOOKMARKS_MENU');" tooltip="bhTooltip" popupsinherittooltip="true" _moz-menupopupstate="open">events.js:297console-output.js:3266
keydown! Object { key: "j", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "j", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "j", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "j", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "j", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "k", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "k", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "k", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297
The object cannot be linked to the inspector without a toolbox
console-output.js:3266
keydown! Object { key: "k", popupPassthrough: true }events.js:61
  popup is open <menupopup id="menu_ToolsPopup" onpopupshowing="setTimeout(() =&gt; gSyncUI.updateUI());" _moz-menupopupstate="open">events.js:297


This was done using my main profile, where the issue isn't resolved after a few seconds like in a clean profile. Sorry for the dirty copy&paste used here to post the logs, unfortunately I found no way to export them but if you want I could try to provide screenshots. I am really grateful for your help, so please don't hestitate to ask if there is anything I can do to make your work easier.

Should I still try out the dev edition of FF or can we skip that step, now that we can make logs this way?

**Comment by lydell** [comment] 2016-09-18 07:28
Thanks! That’s really helpful.

1. A screenshot of the Browser Console would be very good. It feels like everything doesn’t make it through when selecting the text, copying and pasting. What I’m specifically missing is _what_ popup is open.

2. Testing in Firefox Developer Edition would be nice, too. It’s super easy on GNU/Linux – download a tarball, unpack it and run the binary in it. No installation or “system pollution!”

**Comment by fprawits** [comment] 2016-09-18 09:55
Ok, so here is a very minimal example to reproduce the result on my machine and the logs for it:

1. open some homepage
2. two scrolls via "j" (everything fine so far)
3. tap "alt" and type "asdfasdf", tap "alt" again
4. try to scroll again by pressing "j" twice (now not working)

![browser-log](https://cloud.githubusercontent.com/assets/10351100/18614784/fa1863fc-7d95-11e6-962b-38a1c3de469c.png)

I realized that the bug does happen on my main pofile if I just use the HUD without typing in it more often than previously stated; it is just not 100% of the time, so to reproduce this relialbly on my main profile I make sure to always type into the HUD. On the clean profile simply tapping "alt" twice always seems to reproduce this issue (while also fixing itself after a few seconds).

**Comment by lydell** [comment] 2016-09-18 10:02
Summary:

It works in a clean profile, although with that slightly annoying “timeout.”

Personally, I don’t use Unity (and don’t like it after trying it for a year).

So I won’t spend any more time on trying to fix the “timeout” thing.

What you need to do, is to find why things don’t work the same in a clean profile and in your main profile.

If/when more information is unveiled, we can revisit this issue.

And there’s nothing stopping anyone from trying to fix this themselves and send a PR.

So I’m closing this (for now).

**Closed by lydell** 2016-09-18 10:02 UTC
Labels: waiting

**Comment by fprawits** [comment] 2016-09-18 10:25
Just tried a clean profile with 30 tabs open (25 links of a news site, 5 youtube videos on pause) and it is jsut getting weirder:

1. Simply tapping "alt" twice does not reliably reproduce the issue (typing in the HUD still does)
2. I was able to get the "inifinite lock" (or prolonged reset time?) once, although I am not sure what I did differently because trying it again twice afterwards gave me the 3 second reset behaviour again
3. Since I use the clean profile by starting the profile manager via terminal, I noticed that as soon as the bug appears, I get the following output on the terminal:

`
(firefox:9590): LIBDBUSMENU-GTK-CRITICAL **: dbusmenu_menuitem_property_set_shortcut: assertion 'gtk_accelerator_valid(key, modifier)' failed`

**Comment by dspjm** [comment] 2016-11-13 11:36
I have the same problem. I never knew why vimfx just stop working until I saw this bug.

Glad to know disabling and enabling it will work instead to restarting firefox. Will try to stay away from hud.

This addon is amazing, thank the developer.

Well, I hope this bug can be fix as well, though no urgent.

**Comment by ashgillman** [comment] 2017-03-14 00:48
I am also having issues w/ VimFX on Unity. VimFX stops working after switching workspaces. However, I didn't have this issue at any point in my 3-4 weeks of use of VimFX until now.
