### ISSUE TITLE
VimFx doesn't work with LegacyFox under Firefox ESR 68

### ISSUE THREAD

**Issue by archerhush** [akhodakivskiy/VimFx#947] opened 2020-04-20 00:46 UTC
As title says, I'm trying to follow [this](https://gir.st/blog/legacyfox.htm) exact guide to install VimFx with Firefox 68.7.0 ESR x64 under GNU/Linux (Debian).
I git-cloned everything under `/usr/lib/firefox-esr/LegacyFox` and I ran `sudo make install`. It seems tar commands worked out, but when I restarted Firefox I couldn't even install VimFx v0.23.3 through releases page in this repository.
So I manually downloaded it with wget and I tried to install it manually, but it just doesn't show up on Add-ons list.
My console doesn't output anything when I try to install it, while I don't know it's something concerning FX sandbox, but still saying: under my `about:config` I have `security.sandbox.content.level` set to 4 and I even tried to set it to 2 (though it should already be disabled with LegacyFox installation, I think).

**Comment by girst** [comment] 2020-04-20 09:58
On Sun, Apr 19, 2020 at 05:46:25PM -0700, archerhush wrote:
>As title says, I'm trying to follow 
>[this](https://gir.st/blog/legacyfox.htm) exact guide to install VimFx 
>with Firefox 68.7.0 ESR x64 under GNU/Linux (Debian).
>I git-cloned everything under `/usr/lib/firefox-esr` and I ran `sudo 
>make install`. It seems tar commands worked out, but when I restarted 

there is no need to check the repository out in /usr/lib/firefox. make 
install will copy all the files into their proper location.

please try these steps:
cd /tmp  # or ~, or wherever
git clone https://github.com/girst/legacyfox && cd legacyfox
sudo make DESTDIR=/usr/lib/firefox-esr install

you have to define DESTDIR, since the makefile by default assumes 
non-esr firefox.

>Firefox I couldn't even install VimFx v0.23.3 through releases page in 
>this repository.

likely because legacyfox isn't properly installed. that said, there are 
two possible error messages here:
- the addon is corrupt (paraphrased): firefox detected it as a legacy 
   extension and refuses to install it. install legacyfox.
- "The add-on could not be downloaded because of a connection failure."
   i get this when i click on the vimfx.xpi on github. drag the link
   directly onto the urlbar--that'll work.

>My console doesn't output anything when I try to install it, while I 

a quick way of checking if legacyfox is correctly installed is by trying 
to navigate to resource://legacy/BootstrapLoader.jsm (if it exists, the 
installation completed and the firefox config.js is applied).

>don't know it's something concerning FX sandbox, but still saying: 
>under my `about:config` I have `security.sandbox.content.level` set to 
>4 and I even tried to set it to 2.

sandbox is completely unrelated (that's related to vimfx's 
config/frame.js). do not set it lower, add the config path (if you use 
config files) to the whitelist as described in the docs.

**Comment by archerhush** [comment] 2020-04-20 12:39
> On Sun, Apr 19, 2020 at 05:46:25PM -0700, archerhush wrote: As title says, I'm trying to follow [this](https://gir.st/blog/legacyfox.htm) exact guide to install VimFx with Firefox 68.7.0 ESR x64 under GNU/Linux (Debian). I git-cloned everything under `/usr/lib/firefox-esr` and I ran `sudo make install`. It seems tar commands worked out, but when I restarted
> there is no need to check the repository out in /usr/lib/firefox. make install will copy all the files into their proper location. please try these steps: cd /tmp # or ~, or wherever git clone https://github.com/girst/legacyfox && cd legacyfox sudo make DESTDIR=/usr/lib/firefox-esr install you have to define DESTDIR, since the makefile by default assumes non-esr firefox.
> Firefox I couldn't even install VimFx v0.23.3 through releases page in this repository.
> likely because legacyfox isn't properly installed. that said, there are two possible error messages here: - the addon is corrupt (paraphrased): firefox detected it as a legacy extension and refuses to install it. install legacyfox. - "The add-on could not be downloaded because of a connection failure." i get this when i click on the vimfx.xpi on github. drag the link directly onto the urlbar--that'll work.
> My console doesn't output anything when I try to install it, while I
> a quick way of checking if legacyfox is correctly installed is by trying to navigate to resource://legacy/BootstrapLoader.jsm (if it exists, the installation completed and the firefox config.js is applied).
> don't know it's something concerning FX sandbox, but still saying: under my `about:config` I have `security.sandbox.content.level` set to 4 and I even tried to set it to 2.
> sandbox is completely unrelated (that's related to vimfx's config/frame.js). do not set it lower, add the config path (if you use config files) to the whitelist as described in the docs.

Hi, first of all thank you for your collaboration with this add-on in trying to make it survive in any possible way. And yes, I know it's time to get used to some other add-ons and giving up to legacy extensions. Thank you also for giving me your time since you're trying to help me here, I love VimFx and I don't think there is an existing better alternative.

Before doing the installation, I've already did a manually check of `Makefile` and I've already manually changed `DESTDIR` line to `DESTDIR = $(usr/lib/firefox-esr/)`.
I tried to follow your suggestions though, it doesn't work just like before.

**Comment by girst** [comment] 2020-04-20 12:41
On Mon, Apr 20, 2020 at 05:39:24AM -0700, archerhush wrote:
>
>Before doing the installation, I've already did a manually check of 
>`Makefile` and I've already manually changed `DESTDIR` line to `DESTDIR 
>= $(usr/lib/firefox-esr/)`.

this line is wrong. don't wrap the path in $().

**Comment by archerhush** [comment] 2020-04-20 12:47
> On Mon, Apr 20, 2020 at 05:39:24AM -0700, archerhush wrote: Before doing the installation, I've already did a manually check of `Makefile` and I've already manually changed `DESTDIR` line to `DESTDIR = $(usr/lib/firefox-esr/)`.
> this line is wrong. don't wrap the path in $().

Yes, I've just tried without wrapping the path in $() and as I said, I followed your suggestions too (cd /tmp && git cloning there) and then I launched a `sudo make DESTDIR=/usr/lib/firefox-esr install`.
Nothing works though.

**Comment by girst** [comment] 2020-04-20 12:49
hmmmm, stange. two ideas:
please send me
- the output of ls -l /usr/lib/firefox-esr
- the exact error message when attempting to install vimfx.xpi

also, can you try if it works with regular firefox?

**Comment by archerhush** [comment] 2020-04-20 13:01
> hmmmm, stange. two ideas: please send me - the output of ls -l /usr/lib/firefox-esr - the exact error message when attempting to install vimfx.xpi also, can you try if it works with regular firefox?

Sure.
`-rw-r--r-- 1 root root       697 apr  8 00:54 application.ini
drwxr-xr-x 4 root root      4096 apr 16 17:09 browser
-rw-r--r-- 1 root root         0 apr  8 00:54 chrome.manifest
-rw-r--r-- 1 root root       926 apr 20 14:53 config.js
-rwxr-xr-x 1 root root    135080 apr  8 00:54 crashreporter
-rw-r--r-- 1 root root      4003 apr  3 21:30 crashreporter.ini
drwxr-xr-x 3 root root      4096 apr  4 16:54 defaults
-rw-r--r-- 1 root root        72 apr  8 00:54 dependentlibs.list
lrwxrwxrwx 1 root root        36 mar 10 22:59 distribution -> ../../share/firefox-esr/distribution
lrwxrwxrwx 1 root root        11 apr  8 00:54 firefox-bin -> firefox-esr
-rwxr-xr-x 1 root root    224312 apr  8 00:54 firefox-esr
drwxr-xr-x 2 root root      4096 apr 16 17:09 fonts
drwxr-xr-x 3 root root      4096 apr  4 16:54 gmp-clearkey
drwxr-xr-x 2 root root      4096 apr 16 17:09 gtk2
drwxr-xr-x 2 root root      4096 apr 20 14:53 legacy
drwxr-xr-x 5 root root      4096 apr 20 14:44 LegacyFox
-rw-r--r-- 1 root root     18444 apr 20 02:02 legacyfox.tar.gz
-rw-r--r-- 1 root root        24 apr 20 14:53 legacy.manifest
-rw-r--r-- 1 root root     39008 apr  8 00:54 liblgpllibs.so
-rw-r--r-- 1 root root   1814848 apr  8 00:54 libmozavcodec.so
-rw-r--r-- 1 root root    199408 apr  8 00:54 libmozavutil.so
-rw-r--r-- 1 root root     14208 apr  8 00:54 libmozgtk.so
-rw-r--r-- 1 root root    146184 apr  8 00:54 libmozsandbox.so
-rw-r--r-- 1 root root     13968 apr  8 00:54 libmozwayland.so
-rw-r--r-- 1 root root 112077192 apr  8 00:54 libxul.so
-rw-r--r-- 1 root root     16726 apr 20 02:01 LICENSE
-rw-r--r-- 1 root root       488 apr 20 14:37 Makefile
-rwxr-xr-x 1 root root    999872 apr  8 00:54 minidump-analyzer
-rw-r--r-- 1 root root  18421870 apr  8 00:54 omni.ja
-rwxr-xr-x 1 root root    228472 apr  8 00:54 pingsender
-rw-r--r-- 1 root root       164 apr  8 00:54 platform.ini
-rwxr-xr-x 1 root root    215992 apr  8 00:54 plugin-container
-rw-r--r-- 1 root root       960 apr 20 02:01 README
-rw-r--r-- 1 root root       825 apr  3 21:30 Throbber-small.gif`

I've just tried installing a regular Firefox and I've tried your suggestion (`sudo make DESTDIR=/usr/lib/firefox install`), it doesn't work - same result of Firefox-ESR with Firefox 74.0.1 (64-bit).
Oh, I've just tried loading it as a temporary add-on it and it seems almostly to work, but Firefox is telling me "this is an obsolete extension and not supported anymore."

**Comment by girst** [comment] 2020-04-20 13:11
On Mon, Apr 20, 2020 at 06:02:15AM -0700, archerhush wrote:
>> hmmmm, stange. two ideas: please send me - the output of ls -l /usr/lib/firefox-esr - the exact error message when attempting to install vimfx.xpi also, can you try if it works with regular firefox?
>
>Sure.
>-rw-r--r-- 1 root root       926 apr 20 14:53 config.js
>drwxr-xr-x 2 root root      4096 apr 20 14:53 legacy
>-rw-r--r-- 1 root root        24 apr 20 14:53 legacy.manifest

well, files appear to be in the correct location. can you access 
resource://legacy/BootstrapLoader.jsm from within firefox(-esr)?

>Oh, I've just tried loading it as a temporary add-on it and it seems 
>almostly to work, but Firefox is telling me "this is an obsolete 
>extension and not supported anymore."

that suggests an error during startup. close all firefox windows, start 
a new session and immediately press ctrl-shift-j to bring up the browser 
logs. send a screenshot.

i don't have a debian box to test, but i sucessfully installed vimfx in 
a fedora vm with firefox esr downloaded from mozilla.org, so i'm not 
sure what exactly is wrong. it might be, that debian has compiled 
firefox somewhat strange/differently. can you download fx-esr from 
mozilla.org and extract the tarball in your home directory and install 
legacyfox into it?

**Comment by archerhush** [comment] 2020-04-20 13:20
> well, files appear to be in the correct location. can you access resource://legacy/BootstrapLoader.jsm from within firefox(-esr)?

Yes.

> that suggests an error during startup. close all firefox windows, start a new session and immediately press ctrl-shift-j to bring up the browser logs. send a screenshot.

[Here is what you want](https://i.imgur.com/CUUXLZ9.png).

> i don't have a debian box to test, but i sucessfully installed vimfx in a fedora vm with firefox esr downloaded from mozilla.org, so i'm not sure what exactly is wrong. it might be, that debian has compiled firefox somewhat strange/differently. can you download fx-esr from mozilla.org and extract the tarball in your home directory and install legacyfox into it?

Don't worry, it's normal that someone should expect to get something like this since this is the only and non-conventional way of porting a legacy extension with Firefox Quantum. Yes, I'll tell you for sure if it works when it's possible.

**Comment by girst** [comment] 2020-04-20 15:06
ok, i'm at a loss as to why this isn't working on your machine. i 
installed debian 10 (xfce spin, comes with esr) in a vm and installed 
legacyfox and vimfx without any trouble.

all i can still suggest to you is to either reinstall fx-esr (make sure 
that /usr/lib/firefox-esr is gone completely), and/or to try it in a new 
profile. the latter is achieved by starting firefox with 
--ProfileManager and creating a new one.

**Comment by archerhush** [comment] 2020-04-20 15:41
> ok, i'm at a loss as to why this isn't working on your machine. i installed debian 10 (xfce spin, comes with esr) in a vm and installed legacyfox and vimfx without any trouble. all i can still suggest to you is to either reinstall fx-esr (make sure that /usr/lib/firefox-esr is gone completely), and/or to try it in a new profile. the latter is achieved by starting firefox with --ProfileManager and creating a new one.

Err, sorry, when you asked me to give you console errors while trying to install it I get this:

TypeError: (new TypeError("this.addon._repositoryAddon is undefined", "resource://gre/modules/addons/XPIInstall.jsm", 1603)) is not iterable (XPIInstall.jsm:2048:32)

I gave you the wrong console output.

**Comment by girst** [comment] 2020-04-20 16:17
On Mon, Apr 20, 2020 at 08:41:19AM -0700, archerhush wrote:
>TypeError: (new TypeError("this.addon._repositoryAddon is undefined", 
>"resource://gre/modules/addons/XPIInstall.jsm", 1603)) is not iterable 
>(XPIInstall.jsm:2048:32)

without having looked too closely, that suggests to me, the legacy 
extension loader is not loaded properly, and firefox attemts to decode 
webextension-metadata.

i don't have much more advice to you at this point, other than to try to 
eliminate variables. i managed to reproduce it in a fresh copy of 
debian10+esr (the version that ships with the .iso), so that's not it.

**Comment by archerhush** [comment] 2020-04-20 16:22
> On Mon, Apr 20, 2020 at 08:41:19AM -0700, archerhush wrote: TypeError: (new TypeError("this.addon._repositoryAddon is undefined", "resource://gre/modules/addons/XPIInstall.jsm", 1603)) is not iterable (XPIInstall.jsm:2048:32)
> without having looked too closely, that suggests to me, the legacy extension loader is not loaded properly, and firefox attemts to decode webextension-metadata. i don't have much more advice to you at this point, other than to try to eliminate variables. i managed to reproduce it in a fresh copy of debian10+esr (the version that ships with the .iso), so that's not it.

If you get that browser console error when installing and you can still successfully install it, then yeah... it's not the problem.
Also note I have Debian 11 (Debian GNU/Linux bullseye/sid x86_64). Could you try upgrading, uninstalling/reinstalling firefox-esr?

**Comment by girst** [comment] 2020-04-20 16:30
On Mon, Apr 20, 2020 at 09:22:42AM -0700, archerhush wrote:
>Also note I have Debian 11 (Debian GNU/Linux bullseye/sid x86_64). 
>Could you try upgrading, uninstalling/reinstalling firefox-esr?

oh, that vm is gone already. i tried and failed to find a debian 11 iso; 
if you send me a link to one (with a desktop preinstalled), i'll maybe 
try again.

**Comment by archerhush** [comment] 2020-04-20 16:55
> On Mon, Apr 20, 2020 at 09:22:42AM -0700, archerhush wrote: Also note I have Debian 11 (Debian GNU/Linux bullseye/sid x86_64). Could you try upgrading, uninstalling/reinstalling firefox-esr?
> oh, that vm is gone already. i tried and failed to find a debian 11 iso; if you send me a link to one (with a desktop preinstalled), i'll maybe try again.

I don't know if there really Debian 11 iso from the official page, all I did to get it is installing Debian 10 and full-upgrading to Debian 11:

$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get dist-upgrade

these should work for getting into Debian bullseye/sid.

**Comment by archerhush** [comment] 2020-04-21 23:40
@girst do you have any news? I'd appreciate if you make a step-to-step video of you installing everything on Firefox, maybe I'm missing something and I don't know how.

**Comment by girst** [comment] 2020-04-22 05:29
sorry, i don't have the time to record a video. the commands i issued to 
install vimfx+legacyfox i've shared with you previously. reinstall 
firefox and start over in a new profile is all the advice i can give 
you.

**Comment by girst** [comment] 2020-05-05 12:42
closing, since this isn't a bug with vimfx.

if you figure out what was wrong with your environment, please add a comment to this ticket and I'll see if it can be incorporated into the documentation.

**Closed by girst** 2020-05-05 12:42 UTC
Labels: invalid, question
