### ISSUE TITLE
Focus with foreground 'window' elements in page.

### ISSUE THREAD

**Issue by asmyers** [akhodakivskiy/VimFx#799] opened 2016-08-24 14:23 UTC
Thanks for the great addon!

On https://microcorruption.com each level opens with a foreground explanation 'window' which must be clicked through.  Unless I actually mouse click on the window all input goes into the simulated debugger which I can't see.  After I mouse click on the window VimFx can now be used to navigate.

Steps to reproduce:

1.  Start any non-tutorial level at https://microcorruption.com
2. Attempt to scroll or hit 'f' to navigate.
3. Nothing happens. 
4. Click the 'window'
5. Scrolling and navigation now work.
6. Close the 'window', see that input went into the debugger that was behind the window.

Expected result: 

VimFx keys work with the foreground window.

Actual result: 

They don't

VimFx version: 0.18
Firefox version: 48
OS: Ubuntu 16.04
Keyboard language: US
Example URL(s): https://microcorruption.com

**Comment by lydell** [comment] 2016-08-24 15:10
Hi! I started the "New Orleans level". When it loaded, there was a 'window' just like you descibed. But I had no problems whatsoever scrolling or targeting the close button in the 'window' with the `f` command.

VimFx version: 0.18
Firefox version: 48
OS: Ubuntu 16.04
Keyboard language: US

**Comment by asmyers** [comment] 2016-08-24 16:50
I'll see if I can figure out what's causing it, maybe another extension.  It's 100% for me.

**Comment by lydell** [comment] 2016-08-25 05:17
Sorry, now I _can_ reproduce. I accidentally didn't test with default VimFx settings. The thing that happens on that site is that there is a text input in the "Debugger Console" to the right that is autofocused on page load. So when you try to scroll or use other VimFx commands, you actually end up typing in there (check it out – after you close the 'window' that text input should be filled with something like `ddduuuff`).

Here are a few things you can do:

1. Contact the site and tell them that autofocusing a text input _behind_ a "modal" is a terrible idea for accessibility. The modal itself should be focused. (The 'window' is a modal.)

2. Learn to press `<escape>` the first thing you do on that site.

3. Enable the "Prevent autofocus" option (it's off be default, but I had it accidentally enabled when I first tested and therefore couldn't reproduce).

4. If you don't want to prevent autofocus _everywhere,_ you can do so only on this particular site by writing a [config file](https://github.com/akhodakivskiy/VimFx/blob/5ce64b1295cea70c5a789090f8ca33a9bb3610d4/documentation/config-file.md) and add [site-specific customizations](https://github.com/akhodakivskiy/VimFx/blob/5ce64b1295cea70c5a789090f8ca33a9bb3610d4/documentation/api.md#vimfxaddoptionoverrides-and-vimfxaddkeyoverrides) (however, for "Prevent autofocus" that is broken in 0.18.0, but fixed in master, so you'll have to wait for 0.18.1, which will probably be released this weekend.)

**Closed by lydell** 2016-08-25 05:17 UTC
Labels: cannot reproduce

**Comment by asmyers** [comment] 2016-08-26 18:46
That's what I needed, thanks!
